window.SAMOS_DATA = {
  trip: {
    title: "Our Samos Trip",
    dates: "20 to 27 September",
    hotel: "Erato by Samian Mare",
    hotelLat: 37.7907,
    hotelLng: 26.6876
  },

  places: [
    {id:"potami-beach", name:"Potami Beach", area:"Karlovasi", type:"Beach", top15:true, lat:37.7977, lng:26.6548, image:"https://source.unsplash.com/1200x800/?samos,beach,greece", bestFor:["easy first day","swim","near hotel"], tags:["beach","family","near hotel","sunset"], meal:["lunch"], worth:5, family:4, romance:4, beer:2, wine:2, rocco:true, rainy:false, driveHotel:"10 mins", description:"Big scenic pebble beach west of Karlovasi. A very easy first beach from the hotel and a natural pairing with Potami Waterfalls.", timNote:"Good arrival day option. Take beach shoes if you have them.", order:"Look for a simple taverna lunch nearby rather than over planning it.", pairWith:["potami-waterfalls","karlovasi-old-town"], maps:"https://www.google.com/maps/search/?api=1&query=Potami+Beach+Samos"},
    {id:"potami-waterfalls", name:"Potami Waterfalls", area:"Karlovasi", type:"Nature", top15:true, lat:37.7935, lng:26.6595, image:"https://source.unsplash.com/1200x800/?waterfall,forest,greece", bestFor:["adventure","shade","nature"], tags:["nature","family","near hotel","adventure"], meal:["morning"], worth:5, family:3, romance:4, beer:1, wine:1, rocco:true, rainy:false, driveHotel:"10 mins", description:"A forest walk into a gorge with water and small falls. The first part is easy and lovely. The final watery section is more adventurous.", timNote:"Do the walk before lunch. For Rocco, treat the final waterfall section as optional.", order:"Reward yourselves with a lazy lunch afterwards.", pairWith:["potami-beach","karlovasi-old-town"], maps:"https://www.google.com/maps/search/?api=1&query=Potami+Waterfalls+Samos"},
    {id:"kokkari", name:"Kokkari", area:"North coast", type:"Village", top15:true, lat:37.7787, lng:26.8910, image:"https://source.unsplash.com/1200x800/?greek,harbour,village", bestFor:["sunset dinner","harbour wander","restaurants"], tags:["food","views","romantic","family","evening"], meal:["lunch","dinner","drinks"], worth:5, family:4, romance:5, beer:4, wine:4, rocco:true, rainy:true, driveHotel:"40 mins", description:"Probably the village you will want to go back to. Harbour, little streets, beach bars and lots of eating options.", timNote:"Use this as your reliable dinner place when nobody can decide.", order:"Seafood, grilled fish, octopus, local wine and a slow harbour drink.", pairWith:["tsamadou","lemonakia","the-beer-tavern"], maps:"https://www.google.com/maps/search/?api=1&query=Kokkari+Samos"},
    {id:"pythagoreio", name:"Pythagoreio", area:"South coast", type:"Town", top15:true, lat:37.6900, lng:26.9437, image:"https://source.unsplash.com/1200x800/?greek,marina", bestFor:["harbour dinner","history","beer"], tags:["food","history","beer","wine","romantic"], meal:["lunch","dinner","drinks"], worth:5, family:4, romance:5, beer:5, wine:4, rocco:true, rainy:true, driveHotel:"55 mins", description:"Pretty harbour town, good for eating, wandering and combining with Heraion, Panagia Spiliani or Samos Beer.", timNote:"Best as a full south coast day rather than a quick nip out.", order:"Dinner by the harbour, Samos Beer, seafood and something sweet after.", pairWith:["samos-beer","panagia-spiliani","heraion"], maps:"https://www.google.com/maps/search/?api=1&query=Pythagoreio+Samos"},
    {id:"manolates", name:"Manolates", area:"Mountain villages", type:"Village", top15:true, lat:37.7654, lng:26.8247, image:"https://source.unsplash.com/1200x800/?greek,mountain,village", bestFor:["village lunch","views","slow day"], tags:["food","views","romantic","village"], meal:["lunch"], worth:5, family:3, romance:5, beer:2, wine:4, rocco:false, rainy:true, driveHotel:"35 mins", description:"A beautiful mountain village for slow wandering, lunch and views. Best when you want a proper Greek village moment.", timNote:"Lunch territory. Do not rush it.", order:"Local cheese, goat or lamb if on the menu, house wine, honey desserts.", pairWith:["vourliotes","kokkari"], maps:"https://www.google.com/maps/search/?api=1&query=Manolates+Samos"},
    {id:"tsamadou", name:"Tsamadou Beach", area:"Near Kokkari", type:"Beach", top15:true, lat:37.7937, lng:26.8675, image:"https://source.unsplash.com/1200x800/?turquoise,beach,greece", bestFor:["beautiful water","couple beach","views"], tags:["beach","views","romantic","swim"], meal:["lunch"], worth:5, family:3, romance:5, beer:3, wine:2, rocco:false, rainy:false, driveHotel:"40 mins", description:"One of the island's most beautiful beaches, backed by green hills. Better for confident beach days than a toddler splash day.", timNote:"Pair with Kokkari. Check wind before committing.", order:"Beach bar lunch if you are staying put.", pairWith:["kokkari","lemonakia"], maps:"https://www.google.com/maps/search/?api=1&query=Tsamadou+Beach+Samos"},
    {id:"lemonakia", name:"Lemonakia Beach", area:"Near Kokkari", type:"Beach", top15:true, lat:37.7858, lng:26.8737, image:"https://source.unsplash.com/1200x800/?samos,sea", bestFor:["Kokkari day","swim","pretty cove"], tags:["beach","family","views","swim"], meal:["lunch"], worth:4, family:4, romance:4, beer:3, wine:2, rocco:true, rainy:false, driveHotel:"40 mins", description:"A pretty beach near Kokkari and an easy add on for a north coast day.", timNote:"A good compromise beach if you want pretty but still manageable with Rocco.", order:"Keep it simple. Swim, snack, Kokkari later.", pairWith:["kokkari","tsamadou"], maps:"https://www.google.com/maps/search/?api=1&query=Lemonakia+Beach+Samos"},
    {id:"livadaki", name:"Livadaki Beach", area:"North east", type:"Beach", top15:true, lat:37.8008, lng:26.9898, image:"https://source.unsplash.com/1200x800/?shallow,beach,greece", bestFor:["shallow water","family beach","turquoise water"], tags:["beach","family","rocco","swim"], meal:["lunch"], worth:4, family:5, romance:4, beer:2, wine:2, rocco:true, rainy:false, driveHotel:"70 mins", description:"Small, shallow and very pretty. A longer drive from your hotel, but one of the most family friendly beach ideas if conditions are good.", timNote:"Go early. This is not a last minute late afternoon plan from Karlovasi.", order:"Beach snacks and a relaxed lunch nearby.", pairWith:["vathy","samos-wine-museum"], maps:"https://www.google.com/maps/search/?api=1&query=Livadaki+Beach+Samos"},
    {id:"psili-ammos", name:"Psili Ammos", area:"South east", type:"Beach", top15:true, lat:37.7040, lng:27.0131, image:"https://source.unsplash.com/1200x800/?sand,beach,greece", bestFor:["sand","children","shallow sea"], tags:["beach","family","rocco","sand"], meal:["lunch"], worth:4, family:5, romance:3, beer:2, wine:2, rocco:true, rainy:false, driveHotel:"70 mins", description:"A sandy shallow option that makes sense for a proper family beach day when you are happy to cross the island.", timNote:"Good Rocco day, but only if you are already in south east mode.", order:"Beach lunch, ice cream, simple Greek plates.", pairWith:["pythagoreio","heraion"], maps:"https://www.google.com/maps/search/?api=1&query=Psili+Ammos+Beach+Samos"},
    {id:"samos-beer", name:"Samos Beer", area:"Pythagoreio", type:"Beer", top15:true, lat:37.6913, lng:26.9436, image:"https://source.unsplash.com/1200x800/?craft,beer,brewery", bestFor:["local beer","grown up stop","Pythagoreio evening"], tags:["beer","food","local","rainy"], meal:["drinks","dinner"], worth:5, family:2, romance:3, beer:5, wine:1, rocco:false, rainy:true, driveHotel:"55 mins", description:"The island brewery in Pythagoreio. Great if you want a break from standard Greek lager and something genuinely local.", timNote:"Build this into a Pythagoreio day rather than driving only for the brewery.", order:"Try Valsamo Ale if available, then whatever seasonal beer is on.", pairWith:["pythagoreio","panagia-spiliani"], maps:"https://www.google.com/maps/search/?api=1&query=Samos+Beer+Pythagoreio"},
    {id:"samos-wine-museum", name:"Samos Wine Museum", area:"Vathy", type:"Wine", top15:true, lat:37.7548, lng:26.9774, image:"https://source.unsplash.com/1200x800/?wine,museum,vineyard", bestFor:["Muscat","wine context","rainy day"], tags:["wine","rainy","local","culture"], meal:["morning","afternoon"], worth:4, family:2, romance:4, beer:1, wine:5, rocco:false, rainy:true, driveHotel:"55 mins", description:"A useful stop if you want to understand Samos Muscat, sweet wines and the island's wine identity.", timNote:"You will probably enjoy this more than most visitors because of work.", order:"Try sweet Muscat, then look out for dry Muscat afterwards.", pairWith:["vathy","livadaki"], maps:"https://www.google.com/maps/search/?api=1&query=Samos+Wine+Museum"},
    {id:"panagia-spiliani", name:"Panagia Spiliani", area:"Pythagoreio", type:"View", top15:true, lat:37.6965, lng:26.9436, image:"https://source.unsplash.com/1200x800/?greek,monastery,view", bestFor:["views","short visit","south coast day"], tags:["views","history","romantic","culture"], meal:["morning","afternoon"], worth:4, family:3, romance:5, beer:1, wine:1, rocco:false, rainy:true, driveHotel:"55 mins", description:"A cave monastery above Pythagoreio with brilliant views and a sense of theatre.", timNote:"A strong add on before dinner in Pythagoreio.", order:"Not a food stop. Treat it as the view before dinner.", pairWith:["pythagoreio","samos-beer"], maps:"https://www.google.com/maps/search/?api=1&query=Panagia+Spiliani+Samos"},
    {id:"heraion", name:"Heraion of Samos", area:"South coast", type:"History", top15:true, lat:37.6696, lng:26.8846, image:"https://source.unsplash.com/1200x800/?greek,ruins,temple", bestFor:["history","UNESCO","quiet wander"], tags:["history","culture","rainy"], meal:["morning"], worth:4, family:2, romance:3, beer:1, wine:1, rocco:false, rainy:true, driveHotel:"60 mins", description:"One of the island's major ancient sites. Best combined with Pythagoreio or Psili Ammos.", timNote:"Do it early or as a short culture hit, not as a full family day.", order:"Pair with lunch in Pythagoreio.", pairWith:["pythagoreio","psili-ammos"], maps:"https://www.google.com/maps/search/?api=1&query=Heraion+of+Samos"},
    {id:"eupalinos", name:"Tunnel of Eupalinos", area:"Pythagoreio", type:"History", top15:true, lat:37.6959, lng:26.9366, image:"https://source.unsplash.com/1200x800/?ancient,tunnel", bestFor:["ancient engineering","rainy day","history"], tags:["history","rainy","culture"], meal:["morning"], worth:4, family:2, romance:3, beer:1, wine:1, rocco:false, rainy:true, driveHotel:"55 mins", description:"Ancient engineering rather than pretty sightseeing. Memorable, but probably more for adults than Rocco.", timNote:"A good one if you want something clever and different.", order:"Reward with harbour lunch after.", pairWith:["pythagoreio","samos-beer"], maps:"https://www.google.com/maps/search/?api=1&query=Tunnel+of+Eupalinos+Samos"},
    {id:"vourliotes", name:"Vourliotes", area:"Mountain villages", type:"Village", top15:false, lat:37.7682, lng:26.8005, image:"https://source.unsplash.com/1200x800/?greek,village,lane", bestFor:["quiet lunch","village wander"], tags:["food","views","village","quiet"], meal:["lunch"], worth:4, family:3, romance:4, beer:2, wine:4, rocco:false, rainy:true, driveHotel:"35 mins", description:"A quieter village option for lunch and wandering when you want less obvious than Kokkari.", timNote:"Best paired with Manolates or a scenic drive.", order:"Ask what is local or homemade.", pairWith:["manolates"], maps:"https://www.google.com/maps/search/?api=1&query=Vourliotes+Samos"},
    {id:"karlovasi-old-town", name:"Karlovasi Old Town", area:"Karlovasi", type:"Town", top15:false, lat:37.7928, lng:26.7043, image:"https://source.unsplash.com/1200x800/?old,town,greece", bestFor:["near hotel","short wander","low effort"], tags:["near hotel","food","rainy","easy"], meal:["breakfast","lunch","dinner"], worth:3, family:4, romance:3, beer:2, wine:2, rocco:true, rainy:true, driveHotel:"10 mins", description:"Useful because it is close. Explore the old industrial side, cafés and simple local eating.", timNote:"Your low pressure fallback when nobody wants a big drive.", order:"Coffee, bakery bits, simple taverna food.", pairWith:["potami-beach","potami-waterfalls"], maps:"https://www.google.com/maps/search/?api=1&query=Karlovasi+Old+Town+Samos"},
    {id:"vathy", name:"Vathy", area:"Samos Town", type:"Town", top15:false, lat:37.7542, lng:26.9772, image:"https://source.unsplash.com/1200x800/?greek,port,town", bestFor:["shops","wine museum","rainy day"], tags:["food","wine","rainy","shopping"], meal:["lunch","coffee"], worth:3, family:3, romance:3, beer:2, wine:4, rocco:true, rainy:true, driveHotel:"55 mins", description:"Main town area. Useful for shops, cafés, wine museum and a less beachy day.", timNote:"Do not make it the only reason for a long drive, pair it with wine or Livadaki.", order:"Coffee, local sweets, Muscat shopping.", pairWith:["samos-wine-museum","livadaki"], maps:"https://www.google.com/maps/search/?api=1&query=Vathy+Samos"},
    {id:"liknon", name:"Metaxa Liknon", area:"Near Karlovasi", type:"Drink", top15:false, lat:37.7858, lng:26.7056, image:"https://source.unsplash.com/1200x800/?vineyard,terrace,greece", bestFor:["grown up visit","drinks","near hotel"], tags:["drinks","near hotel","rainy","views"], meal:["afternoon"], worth:4, family:2, romance:4, beer:1, wine:3, rocco:false, rainy:true, driveHotel:"10 mins", description:"A nearby grown up stop linked to the home of Metaxa. Check opening and booking details before planning around it.", timNote:"Very convenient from your base if open during your dates.", order:"Treat it as a drinks and place experience rather than a meal.", pairWith:["karlovasi-old-town","potami-beach"], maps:"https://www.google.com/maps/search/?api=1&query=Metaxa+Liknon+Samos"}
  ],

  foodSpots: [
    {id:"cafe-del-mundo", name:"Cafe Del Mundo", area:"Karlovasi", lat:37.792, lng:26.706, image:"https://source.unsplash.com/900x700/?cafe,sea,greece", type:"Cafe", best:["breakfast","lunch","near hotel"], tags:["breakfast","lunch","coffee","family"], price:"££", family:4, romance:3, beer:2, wine:2, summary:"Colourful Karlovasi café noted in recent travel writing. Useful for a near hotel breakfast or lunch without a big drive.", mustOrder:["Coffee","Breakfast plates","Something easy for Rocco"], maps:"https://www.google.com/maps/search/?api=1&query=Cafe+Del+Mundo+Karlovasi+Samos"},
    {id:"dionysos-karlovasi", name:"Dionysos Restaurant", area:"Karlovasi", lat:37.791, lng:26.704, image:"https://source.unsplash.com/900x700/?greek,taverna,food", type:"Taverna", best:["dinner","near hotel"], tags:["dinner","local","family","near hotel"], price:"££", family:4, romance:3, beer:2, wine:3, summary:"A handy Karlovasi restaurant search option for an easy evening close to the hotel.", mustOrder:["Greek salad","Grilled meat or fish","House wine"], maps:"https://www.google.com/maps/search/?api=1&query=Dionysos+Restaurant+Karlovasi+Samos"},
    {id:"the-beer-tavern", name:"The Beer Tavern", area:"Kokkari", lat:37.7787, lng:26.891, image:"https://source.unsplash.com/900x700/?beer,taverna", type:"Beer", best:["dinner","beer","family"], tags:["beer","dinner","kokkari","family"], price:"££", family:5, romance:3, beer:5, wine:2, summary:"A Kokkari option repeatedly surfaced for family friendly eating and beer. Good fit when you want Kokkari but not just wine and seafood.", mustOrder:["Beer","Grilled plates","Something snacky to share"], maps:"https://www.google.com/maps/search/?api=1&query=The+Beer+Tavern+Kokkari+Samos"},
    {id:"zakore", name:"Zakore Restaurant", area:"Kokkari", lat:37.7785, lng:26.8912, image:"https://source.unsplash.com/900x700/?greek,restaurant,terrace", type:"Restaurant", best:["dinner","family","romantic"], tags:["dinner","kokkari","family","romantic"], price:"££", family:4, romance:4, beer:3, wine:3, summary:"A popular Kokkari restaurant option that is useful for a harbour village dinner shortlist.", mustOrder:["Seafood","Greek starters","Local wine"], maps:"https://www.google.com/maps/search/?api=1&query=Zakore+Restaurant+Kokkari+Samos"},
    {id:"wave-cafe", name:"Wave Cafe Bar", area:"Kokkari", lat:37.7786, lng:26.8905, image:"https://source.unsplash.com/900x700/?cafe,bar,sea", type:"Cafe Bar", best:["breakfast","drinks","views"], tags:["breakfast","drinks","kokkari","view"], price:"££", family:4, romance:4, beer:3, wine:3, summary:"Good candidate for coffee, drinks or a pause in Kokkari rather than a full taverna meal.", mustOrder:["Coffee","Cold drink","Dessert or snack"], maps:"https://www.google.com/maps/search/?api=1&query=Wave+Cafe+Bar+Kokkari+Samos"},
    {id:"samia-restaurant", name:"Samia Restaurant", area:"Kokkari", lat:37.7784, lng:26.8906, image:"https://source.unsplash.com/900x700/?greek,seafood,harbour", type:"Taverna", best:["lunch","dinner","family"], tags:["lunch","dinner","kokkari","seafood"], price:"££", family:4, romance:4, beer:2, wine:3, summary:"A Kokkari family friendly restaurant option for lunch or dinner.", mustOrder:["Fish","Octopus","Greek salad"], maps:"https://www.google.com/maps/search/?api=1&query=Samia+Restaurant+Kokkari+Samos"},
    {id:"four-seasons-pythagoreio", name:"Four Seasons", area:"Pythagoreio", lat:37.6901, lng:26.9437, image:"https://source.unsplash.com/900x700/?harbour,restaurant,greece", type:"Restaurant", best:["dinner","family"], tags:["dinner","pythagoreio","family"], price:"££", family:4, romance:4, beer:2, wine:3, summary:"A Pythagoreio restaurant option that appears in popular family friendly lists.", mustOrder:["Seafood","Greek mains","Local wine"], maps:"https://www.google.com/maps/search/?api=1&query=Four+Seasons+Restaurant+Pythagoreio+Samos"},
    {id:"knife-fork", name:"Knife & Fork", area:"Pythagoreio", lat:37.6901, lng:26.9442, image:"https://source.unsplash.com/900x700/?modern,restaurant,greece", type:"Restaurant", best:["dinner","special"], tags:["dinner","pythagoreio","special"], price:"£££", family:3, romance:5, beer:2, wine:4, summary:"A more polished Pythagoreio dinner option for a grown up evening or special meal.", mustOrder:["Ask for specials","Wine pairing","Dessert"], maps:"https://www.google.com/maps/search/?api=1&query=Knife+and+Fork+Pythagoreio+Samos"},
    {id:"two-spoons", name:"Two Spoons", area:"Pythagoreio", lat:37.6901, lng:26.9438, image:"https://source.unsplash.com/900x700/?dessert,cafe,greece", type:"Cafe", best:["breakfast","dessert","coffee"], tags:["breakfast","coffee","dessert","pythagoreio"], price:"££", family:5, romance:3, beer:1, wine:1, summary:"A handy café and sweet stop in Pythagoreio, useful with Rocco or after dinner.", mustOrder:["Coffee","Cake","Ice cream or dessert"], maps:"https://www.google.com/maps/search/?api=1&query=Two+Spoons+Pythagoreio+Samos"},
    {id:"garlic", name:"Garlic", area:"Pythagoreio", lat:37.6902, lng:26.9439, image:"https://source.unsplash.com/900x700/?gyros,greek,food", type:"Casual", best:["lunch","value","quick"], tags:["lunch","quick","pythagoreio","family"], price:"£", family:4, romance:2, beer:2, wine:1, summary:"A casual Pythagoreio option for quick, lower fuss food.", mustOrder:["Gyros","Souvlaki","Chips for Rocco"], maps:"https://www.google.com/maps/search/?api=1&query=Garlic+Pythagoreio+Samos"},
    {id:"asteria-pythagorion", name:"Asteria", area:"Pythagoreio", lat:37.690, lng:26.944, image:"https://source.unsplash.com/900x700/?seafood,terrace,greece", type:"Restaurant", best:["dinner","seafood"], tags:["dinner","seafood","pythagoreio"], price:"££", family:3, romance:4, beer:2, wine:3, summary:"A Pythagoreio dinner candidate from recent restaurant roundups. Check recent reviews before committing.", mustOrder:["Seafood","Grilled fish","Local wine"], maps:"https://www.google.com/maps/search/?api=1&query=Asteria+Pythagorion+Samos"},
    {id:"navagos", name:"Navagos Beach Bar", area:"Livadaki", lat:37.8008, lng:26.9898, image:"https://source.unsplash.com/900x700/?beach,bar,greece", type:"Beach Bar", best:["lunch","beach","drinks"], tags:["lunch","drinks","beach","family"], price:"££", family:4, romance:4, beer:3, wine:2, summary:"A useful beach bar idea if you make the drive to Livadaki.", mustOrder:["Cold beer","Beach lunch","Ice cream or soft drink"], maps:"https://www.google.com/maps/search/?api=1&query=Navagos+Beach+Bar+Samos"},
    {id:"ormos-marathokampou", name:"Ormos Marathokampou tavernas", area:"South west", lat:37.708, lng:26.683, image:"https://source.unsplash.com/900x700/?greek,fishing,village", type:"Taverna Area", best:["lunch","seafood","drive"], tags:["lunch","dinner","seafood","views"], price:"££", family:4, romance:4, beer:2, wine:3, summary:"A good area to consider for seafood by the sea if exploring the south west.", mustOrder:["Fresh fish","Octopus","Greek salad"], maps:"https://www.google.com/maps/search/?api=1&query=Ormos+Marathokampou+restaurants+Samos"},
    {id:"ireo-tavernas", name:"Ireo seafront tavernas", area:"South coast", lat:37.666, lng:26.883, image:"https://source.unsplash.com/900x700/?seafront,taverna,greece", type:"Taverna Area", best:["lunch","dinner","seafood"], tags:["lunch","dinner","seafood","family"], price:"££", family:4, romance:4, beer:2, wine:3, summary:"A useful food area near Heraion for a south coast day.", mustOrder:["Fish","Calamari","Local wine"], maps:"https://www.google.com/maps/search/?api=1&query=Ireo+restaurants+Samos"}
  ],

  dishes: [
    {id:"revithokeftedes", name:"Revithokeftedes", greek:"Ρεβιθοκεφτέδες", pronounce:"reh vee tho kef TEH des", image:"https://source.unsplash.com/900x700/?chickpea,fritters", category:"local", worth:5, description:"Chickpea fritters. One of the local items to actively look for.", lookFor:["chickpea fritters","vegetarian starter","meze"]},
    {id:"giouvetsi", name:"Giouvetsi", greek:"Γιουβέτσι", pronounce:"you VET see", image:"https://source.unsplash.com/900x700/?orzo,lamb", category:"local", worth:5, description:"Slow cooked meat with orzo pasta. Comfort food and good for a proper taverna meal.", lookFor:["lamb giouvetsi","beef giouvetsi","orzo"]},
    {id:"bourekia", name:"Bourekia", greek:"Μπουρέκια", pronounce:"boo REH kya", image:"https://source.unsplash.com/900x700/?greek,pastry", category:"local", worth:4, description:"Traditional pastries, often with pumpkin or cheese depending on the version.", lookFor:["pumpkin pastry","cheese pastry","local pastry"]},
    {id:"dermatotyri", name:"Dermatotyri", greek:"Δερματοτύρι", pronounce:"der ma to TEE ree", image:"https://source.unsplash.com/900x700/?greek,cheese", category:"local", worth:4, description:"A distinctive local cheese. Ask for local cheese if you do not see the name.", lookFor:["local cheese","cheese with honey","village cheese"]},
    {id:"kolokythoanthoi", name:"Stuffed courgette flowers", greek:"Κολοκυθοανθοί", pronounce:"ko lo kee tho an THEE", image:"https://source.unsplash.com/900x700/?stuffed,zucchini,flowers", category:"local", worth:4, description:"Courgette flowers usually stuffed with rice or herbs. Order if on a specials board.", lookFor:["stuffed flowers","courgette flowers","zucchini flowers"]},
    {id:"htapodi", name:"Octopus", greek:"Χταπόδι", pronounce:"hta PO thee", image:"https://source.unsplash.com/900x700/?grilled,octopus", category:"seafood", worth:5, description:"Usually grilled or served in vinegar. Hanging octopus outside a taverna is often a good sign.", lookFor:["grilled octopus","octopus in vinegar","xtapodi"]},
    {id:"kalamari", name:"Squid", greek:"Καλαμάρι", pronounce:"ka la MA ree", image:"https://source.unsplash.com/900x700/?calamari", category:"seafood", worth:4, description:"Usually grilled or fried. Easy family friendly seafood if you know you like it.", lookFor:["fried calamari","grilled calamari","squid"]},
    {id:"garides", name:"Prawns", greek:"Γαρίδες", pronounce:"ga REE thes", image:"https://source.unsplash.com/900x700/?prawns,seafood", category:"seafood", worth:4, description:"Prawns. Often grilled, saganaki style or with pasta.", lookFor:["shrimp saganaki","grilled prawns","prawns"]},
    {id:"moussaka", name:"Moussaka", greek:"Μουσακάς", pronounce:"moo sa KAS", image:"https://source.unsplash.com/900x700/?moussaka", category:"classic", worth:3, description:"Layered aubergine, meat and béchamel. Common, filling and easy to recognise.", lookFor:["moussaka","aubergine bake"]},
    {id:"souvlaki", name:"Souvlaki", greek:"Σουβλάκι", pronounce:"soo VLA kee", image:"https://source.unsplash.com/900x700/?souvlaki", category:"classic", worth:3, description:"Grilled meat skewer or wrap. Useful quick food with a child.", lookFor:["chicken souvlaki","pork souvlaki","gyros"]},
    {id:"loukoumades", name:"Loukoumades", greek:"Λουκουμάδες", pronounce:"loo koo MA thes", image:"https://source.unsplash.com/900x700/?honey,doughnuts", category:"sweet", worth:4, description:"Greek honey doughnuts. Good dessert or treat if you find them.", lookFor:["honey balls","Greek doughnuts","loukoumades"]},
    {id:"muscat", name:"Samos Muscat", greek:"Μοσχάτο Σάμου", pronounce:"mos HA to SA mou", image:"https://source.unsplash.com/900x700/?muscat,wine", category:"drink", worth:5, description:"The island's signature wine. Try sweet Vin Doux and look for dry Muscat too.", lookFor:["Vin Doux","Anthemis","dry Muscat"]},
    {id:"samos-beer-dish", name:"Samos Beer", greek:"Μπύρα Σάμου", pronounce:"BEE ra SA mou", image:"https://source.unsplash.com/900x700/?craft,beer", category:"drink", worth:5, description:"Local island beer. Look for Valsamo Ale and brewery pours in Pythagoreio.", lookFor:["Valsamo","Samos Beer","local beer"]}
  ],

  phrases: [
    {cat:"Basics", en:"Hello", el:"Γεια σας", pr:"Yassas"},
    {cat:"Basics", en:"Good morning", el:"Καλημέρα", pr:"Kalimera"},
    {cat:"Basics", en:"Good evening", el:"Καλησπέρα", pr:"Kalispera"},
    {cat:"Basics", en:"Thank you", el:"Ευχαριστώ", pr:"Efharisto"},
    {cat:"Basics", en:"Please", el:"Παρακαλώ", pr:"Parakalo"},
    {cat:"Basics", en:"Sorry", el:"Συγγνώμη", pr:"Signomi"},
    {cat:"Restaurant", en:"A table for three please", el:"Ένα τραπέζι για τρεις παρακαλώ", pr:"Ena trapezi gia tris parakalo"},
    {cat:"Restaurant", en:"The menu please", el:"Το μενού παρακαλώ", pr:"To menu parakalo"},
    {cat:"Restaurant", en:"The bill please", el:"Τον λογαριασμό παρακαλώ", pr:"Ton logariasmo parakalo"},
    {cat:"Restaurant", en:"Water please", el:"Νερό παρακαλώ", pr:"Nero parakalo"},
    {cat:"Restaurant", en:"House wine please", el:"Κρασί χύμα παρακαλώ", pr:"Krasi heema parakalo"},
    {cat:"Restaurant", en:"One beer please", el:"Μία μπύρα παρακαλώ", pr:"Mia bira parakalo"},
    {cat:"Restaurant", en:"What do you recommend?", el:"Τι προτείνετε;", pr:"Ti protinete"},
    {cat:"Child", en:"Do you have a high chair?", el:"Έχετε παιδικό κάθισμα;", pr:"Ehete pediko kathisma"},
    {cat:"Child", en:"For a child please", el:"Για παιδί παρακαλώ", pr:"Ya pedi parakalo"},
    {cat:"Directions", en:"Where is the toilet?", el:"Πού είναι η τουαλέτα;", pr:"Pou ine i toualeta"},
    {cat:"Directions", en:"Where is the beach?", el:"Πού είναι η παραλία;", pr:"Pou ine i paralia"},
    {cat:"Driving", en:"Petrol", el:"Βενζίνη", pr:"Venzini"},
    {cat:"Driving", en:"Diesel", el:"Πετρέλαιο", pr:"Petreleo"},
    {cat:"Driving", en:"Fill it up please", el:"Γεμίστε το παρακαλώ", pr:"Yemiste to parakalo"},
    {cat:"Shop", en:"How much is it?", el:"Πόσο κάνει;", pr:"Poso kani"},
    {cat:"Pharmacy", en:"I need a pharmacy", el:"Χρειάζομαι φαρμακείο", pr:"Hriazome farmakio"},
    {cat:"Emergency", en:"I need help", el:"Χρειάζομαι βοήθεια", pr:"Hriazome voithia"}
  ],

  dayPlans: [
    {id:"easy-potami", title:"Easy Potami Day", mood:["knackered","beach","family","near"], stops:["potami-waterfalls","potami-beach","karlovasi-old-town"], summary:"The best low effort day from your hotel. Nature first, beach after, easy evening."},
    {id:"kokkari-postcard", title:"Postcard Kokkari Day", mood:["normal","food","views","romantic"], stops:["lemonakia","tsamadou","kokkari"], summary:"The classic north coast day. Pretty beach, harbour dinner and no need to overthink it."},
    {id:"south-history", title:"History And Harbour", mood:["adventure","history","food"], stops:["heraion","panagia-spiliani","pythagoreio","samos-beer"], summary:"A full south coast day with history, views, harbour and beer."},
    {id:"mountain-lunch", title:"Mountain Village Lunch", mood:["normal","food","romantic","views"], stops:["manolates","vourliotes","kokkari"], summary:"Slow village wandering, proper lunch and optional evening by the sea."},
    {id:"wine-day", title:"Muscat And Local Flavour", mood:["normal","wine","rainy"], stops:["samos-wine-museum","vathy","livadaki"], summary:"Good for the wine brain. Learn Samos Muscat, then add town or beach depending on weather."},
    {id:"rocco-splash", title:"Rocco Splash Day", mood:["family","beach","rocco"], stops:["psili-ammos","pythagoreio"], summary:"A longer drive, but a good shallow water family day with an easy harbour reward."}
  ],

  tryList: [
    {id:"try-revithokeftedes", type:"Food", text:"Revithokeftedes"},
    {id:"try-giouvetsi", type:"Food", text:"Giouvetsi"},
    {id:"try-bourekia", type:"Food", text:"Bourekia"},
    {id:"try-octopus", type:"Food", text:"Grilled octopus"},
    {id:"try-dermatotyri", type:"Food", text:"Local cheese"},
    {id:"try-vindoux", type:"Wine", text:"Samos Vin Doux"},
    {id:"try-dry-muscat", type:"Wine", text:"Dry Muscat"},
    {id:"try-samos-beer", type:"Beer", text:"Samos Beer"},
    {id:"try-honey", type:"Sweet", text:"Local honey or honey dessert"}
  ]
};
