window.SAMOS_DATA = {
  hotel: {
    name: "Erato by Samian Mare",
    lat: 37.7917,
    lng: 26.7046,
    maps: "https://www.google.com/maps/search/?api=1&query=Erato+by+Samian+Mare+Samos"
  },
  heroImages: [
    "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80"
  ],
  places: [
    {
      id: "potami-beach",
      name: "Potami Beach",
      area: "Karlovasi",
      category: "beach",
      top: true,
      lat: 37.7972,
      lng: 26.6509,
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      summary: "The easy first beach from your hotel. Big views, clear water, pebbles and a very good arrival day feel.",
      bestFor: ["First full day", "Sea air", "Low effort", "Sunset wander"],
      avoidIf: "You need soft sand or totally calm shallow water for a long toddler swim.",
      facilities: ["Parking nearby", "Food nearby", "Pebble beach", "Good with water shoes"],
      kid: 8,
      romance: 8,
      driveFromHotel: "10 mins",
      pairWith: ["Potami Waterfalls", "Karlovasi Old Town"],
      tags: ["near hotel", "beach", "views", "family"],
      maps: "https://www.google.com/maps/search/?api=1&query=Potami+Beach+Samos"
    },
    {
      id: "potami-waterfalls",
      name: "Potami Waterfalls",
      area: "Karlovasi",
      category: "experience",
      top: true,
      lat: 37.7894,
      lng: 26.6562,
      image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80",
      summary: "Forest walk, stream, gorge and waterfalls. Do the gentle first part with Rocco, then judge the adventurous section when you get there.",
      bestFor: ["Adventure morning", "Shade", "Photos", "Something different"],
      avoidIf: "Everyone is tired, you are not wearing decent shoes, or you do not fancy getting wet.",
      facilities: ["Walk from Potami area", "Water shoes useful", "Not buggy friendly", "Good early in the day"],
      kid: 7,
      romance: 9,
      driveFromHotel: "10 mins",
      pairWith: ["Potami Beach", "Lunch near Potami"],
      tags: ["near hotel", "nature", "walk", "adventure"],
      maps: "https://www.google.com/maps/search/?api=1&query=Potami+Waterfalls+Samos"
    },
    {
      id: "kokkari",
      name: "Kokkari",
      area: "North coast",
      category: "village",
      top: true,
      lat: 37.7787,
      lng: 26.8915,
      image: "https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?auto=format&fit=crop&w=1200&q=80",
      summary: "The postcard harbour village. This is the one for an evening wander, seafood, drinks and honeymoon photos.",
      bestFor: ["Dinner", "Sunset", "Harbour wander", "Couple time"],
      avoidIf: "You want totally quiet or very easy parking at peak dinner time.",
      facilities: ["Restaurants", "Bars", "Harbour", "Shops"],
      kid: 8,
      romance: 10,
      driveFromHotel: "35 to 45 mins",
      pairWith: ["Lemonakia Beach", "Tsamadou Beach", "Vourliotes"],
      tags: ["food", "romantic", "evening", "views"],
      maps: "https://www.google.com/maps/search/?api=1&query=Kokkari+Samos"
    },
    {
      id: "lemonakia",
      name: "Lemonakia Beach",
      area: "Near Kokkari",
      category: "beach",
      top: true,
      lat: 37.7797,
      lng: 26.8750,
      image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
      summary: "Pretty cove near Kokkari. A strong beach choice when you want a scenic swim plus an easy harbour meal afterwards.",
      bestFor: ["Kokkari day", "Clear water", "Couples", "Scenic swim"],
      avoidIf: "You need lots of sand or a huge open beach.",
      facilities: ["Sunbeds in season", "Food nearby", "Pebbles", "Water shoes useful"],
      kid: 7,
      romance: 9,
      driveFromHotel: "40 mins",
      pairWith: ["Kokkari", "Tsamadou Beach"],
      tags: ["beach", "views", "swim", "food nearby"],
      maps: "https://www.google.com/maps/search/?api=1&query=Lemonakia+Beach+Samos"
    },
    {
      id: "tsamadou",
      name: "Tsamadou Beach",
      area: "Near Kokkari",
      category: "beach",
      top: true,
      lat: 37.7819,
      lng: 26.8639,
      image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      summary: "One of the island beauty spots. Pine backed, clear water and more dramatic than most family beaches.",
      bestFor: ["Scenery", "Swimming", "Photos", "A proper beach day"],
      avoidIf: "You need very easy access or a soft sandy toddler beach.",
      facilities: ["Sunbeds in season", "Beach bars", "Pebbles", "Some steep access"],
      kid: 6,
      romance: 9,
      driveFromHotel: "40 mins",
      pairWith: ["Kokkari", "Lemonakia Beach"],
      tags: ["beach", "views", "romantic", "swim"],
      maps: "https://www.google.com/maps/search/?api=1&query=Tsamadou+Beach+Samos"
    },
    {
      id: "livadaki",
      name: "Livadaki Beach",
      area: "North east",
      category: "beach",
      top: true,
      lat: 37.7953,
      lng: 26.9997,
      image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=80",
      summary: "Small turquoise cove with shallow water. A brilliant family beach if the drive feels worth it.",
      bestFor: ["Rocco swim", "Shallow water", "Photos", "Calm beach mood"],
      avoidIf: "You want a short drive or dislike rougher access roads.",
      facilities: ["Beach bar in season", "Shallow water", "Limited space", "Arrive early"],
      kid: 9,
      romance: 8,
      driveFromHotel: "60 to 70 mins",
      pairWith: ["Vathy", "Samos Wine Museum"],
      tags: ["beach", "family", "shallow", "worth the drive"],
      maps: "https://www.google.com/maps/search/?api=1&query=Livadaki+Beach+Samos"
    },
    {
      id: "psili-ammos-east",
      name: "Psili Ammos Beach",
      area: "South east",
      category: "beach",
      top: true,
      lat: 37.7039,
      lng: 27.0189,
      image: "https://images.unsplash.com/photo-1520942702018-0862200e6873?auto=format&fit=crop&w=1200&q=80",
      summary: "Sandy and shallow, which makes it one of the more useful beaches with a small child.",
      bestFor: ["Sand", "Shallow water", "Family day", "Easy paddling"],
      avoidIf: "You want a short hop from Karlovasi.",
      facilities: ["Sand", "Tavernas nearby", "Shallow sea", "Family friendly"],
      kid: 9,
      romance: 6,
      driveFromHotel: "70 mins",
      pairWith: ["Pythagoreio", "Heraion"],
      tags: ["beach", "family", "sand", "shallow"],
      maps: "https://www.google.com/maps/search/?api=1&query=Psili+Ammos+Beach+Samos"
    },
    {
      id: "pythagoreio",
      name: "Pythagoreio",
      area: "South coast",
      category: "town",
      top: true,
      lat: 37.6901,
      lng: 26.9434,
      image: "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=1200&q=80",
      summary: "Harbour town, dinner spot, history base and the easiest place to combine ancient sites with evening drinks.",
      bestFor: ["Harbour dinner", "History day", "Cocktails", "Wandering"],
      avoidIf: "Nobody has the energy for a longer cross island day.",
      facilities: ["Restaurants", "Bars", "Shops", "Harbour"],
      kid: 8,
      romance: 9,
      driveFromHotel: "50 to 60 mins",
      pairWith: ["Tunnel of Eupalinos", "Panagia Spiliani", "Samos Beer"],
      tags: ["food", "history", "evening", "harbour"],
      maps: "https://www.google.com/maps/search/?api=1&query=Pythagoreio+Samos"
    },
    {
      id: "samos-beer",
      name: "Samos Beer",
      area: "Pythagoreio",
      category: "beer",
      top: true,
      lat: 37.6908,
      lng: 26.9443,
      image: "https://images.unsplash.com/photo-1532635241-17e820acc59f?auto=format&fit=crop&w=1200&q=80",
      summary: "The local brewery stop. Good for ticking off proper island beer rather than defaulting to Mythos all week.",
      bestFor: ["Local beer", "Pythagoreio day", "Grown up treat", "Souvenir bottles"],
      avoidIf: "You are driving and nobody else wants to share the beer burden responsibly.",
      facilities: ["Brewery", "Beer", "Food likely", "Check hours before travelling"],
      kid: 4,
      romance: 7,
      driveFromHotel: "55 mins",
      pairWith: ["Pythagoreio", "Tunnel of Eupalinos"],
      tags: ["beer", "local", "pythagoreio", "grown up"],
      maps: "https://www.google.com/maps/search/?api=1&query=Samos+Beer+Pythagoreio"
    },
    {
      id: "samos-wine-museum",
      name: "Samos Wine Museum",
      area: "Vathy",
      category: "wine",
      top: true,
      lat: 37.7560,
      lng: 26.9760,
      image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80",
      summary: "The obvious wine geek stop. Use it to understand why Samos Muscat is the island's calling card.",
      bestFor: ["Wine context", "Rainy hour", "Muscat", "Souvenir bottle"],
      avoidIf: "You want a full vineyard visit rather than a museum style stop.",
      facilities: ["Wine", "Museum", "Indoor", "Shop"],
      kid: 4,
      romance: 8,
      driveFromHotel: "45 to 55 mins",
      pairWith: ["Vathy", "Livadaki Beach"],
      tags: ["wine", "rainy day", "local", "muscat"],
      maps: "https://www.google.com/maps/search/?api=1&query=Samos+Wine+Museum"
    },
    {
      id: "metaxa-liknon",
      name: "Metaxa Liknon",
      area: "Vourliotes area",
      category: "wine",
      top: true,
      lat: 37.7660,
      lng: 26.8250,
      image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80",
      summary: "A very polished Samos Muscat experience. Worth considering if you want wine, views and a more designed visitor experience.",
      bestFor: ["Wine", "Views", "Honeymoon treat", "Photos"],
      avoidIf: "You want old school rustic taverna energy only.",
      facilities: ["Wine experience", "Views", "Book ahead", "Check seasonal opening"],
      kid: 5,
      romance: 10,
      driveFromHotel: "30 to 40 mins",
      pairWith: ["Vourliotes", "Manolates"],
      tags: ["wine", "views", "romantic", "muscat"],
      maps: "https://www.google.com/maps/search/?api=1&query=Metaxa+Liknon+Samos"
    },
    {
      id: "manolates",
      name: "Manolates",
      area: "Mountain village",
      category: "village",
      top: true,
      lat: 37.7623,
      lng: 26.8351,
      image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
      summary: "Mountain village lunch territory. Narrow lanes, views, cats, slow food and a very different feel from the coast.",
      bestFor: ["Long lunch", "Views", "Slow wander", "Romantic afternoon"],
      avoidIf: "You need buggy friendly pavements or lots of entertainment for a restless child.",
      facilities: ["Tavernas", "Craft shops", "Village lanes", "Views"],
      kid: 6,
      romance: 9,
      driveFromHotel: "30 to 40 mins",
      pairWith: ["Vourliotes", "Metaxa Liknon"],
      tags: ["village", "food", "views", "romantic"],
      maps: "https://www.google.com/maps/search/?api=1&query=Manolates+Samos"
    },
    {
      id: "vourliotes",
      name: "Vourliotes",
      area: "Mountain village",
      category: "village",
      top: true,
      lat: 37.7626,
      lng: 26.8427,
      image: "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=1200&q=80",
      summary: "A quieter hill village option. Good for lunch, views and getting away from obvious beach resort rhythms.",
      bestFor: ["Lunch", "Quiet", "Views", "Local feel"],
      avoidIf: "You want a packed list of things to do rather than a slow village stop.",
      facilities: ["Tavernas", "Views", "Village square", "Mountain roads"],
      kid: 6,
      romance: 8,
      driveFromHotel: "35 to 45 mins",
      pairWith: ["Manolates", "Metaxa Liknon"],
      tags: ["village", "food", "views", "quiet"],
      maps: "https://www.google.com/maps/search/?api=1&query=Vourliotes+Samos"
    },
    {
      id: "heraion",
      name: "Heraion of Samos",
      area: "South coast",
      category: "history",
      top: true,
      lat: 37.6717,
      lng: 26.8855,
      image: "https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?auto=format&fit=crop&w=1200&q=80",
      summary: "One of the big ancient sites of Samos. Better as a focused morning stop than a long child led afternoon.",
      bestFor: ["History", "UNESCO context", "Morning visit", "Culture"],
      avoidIf: "It is blazing hot or Rocco has no interest in ruins that day.",
      facilities: ["Ancient site", "Limited shade", "Go early", "Pair with lunch"],
      kid: 5,
      romance: 7,
      driveFromHotel: "55 to 65 mins",
      pairWith: ["Pythagoreio", "Psili Ammos Beach"],
      tags: ["history", "culture", "unesco", "south"],
      maps: "https://www.google.com/maps/search/?api=1&query=Heraion+of+Samos"
    },
    {
      id: "eupalinos",
      name: "Tunnel of Eupalinos",
      area: "Pythagoreio",
      category: "history",
      top: true,
      lat: 37.6966,
      lng: 26.9421,
      image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80",
      summary: "Ancient engineering, cool underground atmosphere and a good grown up history hit near Pythagoreio.",
      bestFor: ["History", "Rainy option", "Engineering", "Culture"],
      avoidIf: "Small spaces, uneven footing or child patience are an issue.",
      facilities: ["Book or check tours", "Closed shoes", "Indoor", "Near Pythagoreio"],
      kid: 4,
      romance: 6,
      driveFromHotel: "55 mins",
      pairWith: ["Pythagoreio", "Panagia Spiliani"],
      tags: ["history", "rainy day", "culture", "pythagoreio"],
      maps: "https://www.google.com/maps/search/?api=1&query=Tunnel+of+Eupalinos+Samos"
    },
    {
      id: "panagia-spiliani",
      name: "Panagia Spiliani Monastery",
      area: "Pythagoreio",
      category: "viewpoint",
      top: true,
      lat: 37.6976,
      lng: 26.9439,
      image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      summary: "Cave monastery and big views above Pythagoreio. A really good add on to a south coast day.",
      bestFor: ["Views", "Short visit", "Culture", "Photos"],
      avoidIf: "You need completely step free access.",
      facilities: ["Views", "Cave", "Religious site", "Near Pythagoreio"],
      kid: 6,
      romance: 9,
      driveFromHotel: "55 mins",
      pairWith: ["Pythagoreio", "Tunnel of Eupalinos"],
      tags: ["views", "history", "culture", "romantic"],
      maps: "https://www.google.com/maps/search/?api=1&query=Panagia+Spiliani+Samos"
    },
    {
      id: "karlovasi-old-town",
      name: "Karlovasi Old Town",
      area: "Karlovasi",
      category: "town",
      top: false,
      lat: 37.7927,
      lng: 26.7040,
      image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
      summary: "Useful because it is local. Good for an easy wander, supplies and getting your bearings without a big drive.",
      bestFor: ["Near hotel", "Low effort", "Shops", "Evening wander"],
      avoidIf: "You want the classic pretty harbour village look of Kokkari or Pythagoreio.",
      facilities: ["Shops", "Cafes", "Supermarkets", "Local town"],
      kid: 7,
      romance: 5,
      driveFromHotel: "5 mins",
      pairWith: ["Potami Beach", "Hotel pool time"],
      tags: ["near hotel", "town", "practical", "easy"],
      maps: "https://www.google.com/maps/search/?api=1&query=Karlovasi+Samos"
    },
    {
      id: "mikro-seitani",
      name: "Mikro Seitani",
      area: "West coast",
      category: "beach",
      top: false,
      lat: 37.8151,
      lng: 26.6232,
      image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
      summary: "Wild, beautiful and more adventurous. Keep it as an adult energy day rather than the default child plan.",
      bestFor: ["Adventure", "Wild beach", "Photos", "Quiet"],
      avoidIf: "You need facilities, easy access or a guaranteed child friendly setup.",
      facilities: ["No real facilities", "Walk required", "Wild beach", "Take water"],
      kid: 3,
      romance: 8,
      driveFromHotel: "Drive plus walk",
      pairWith: ["Potami Beach"],
      tags: ["beach", "adventure", "wild", "views"],
      maps: "https://www.google.com/maps/search/?api=1&query=Mikro+Seitani+Samos"
    },
    {
      id: "megalo-seitani",
      name: "Megalo Seitani",
      area: "West coast",
      category: "beach",
      top: false,
      lat: 37.8264,
      lng: 26.6119,
      image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=80",
      summary: "Remote big beach and nature reserve energy. Beautiful, but not a casual toddler stop.",
      bestFor: ["Hiking", "Wild coast", "Quiet", "Adventure"],
      avoidIf: "You want sunbeds, toilets, food or an easy short visit.",
      facilities: ["Remote", "Walk required", "No facilities", "Take supplies"],
      kid: 2,
      romance: 8,
      driveFromHotel: "Drive plus longer walk",
      pairWith: ["Mikro Seitani"],
      tags: ["beach", "adventure", "wild", "walk"],
      maps: "https://www.google.com/maps/search/?api=1&query=Megalo+Seitani+Samos"
    },
    {
      id: "votsalakia",
      name: "Votsalakia Beach",
      area: "Marathokampos",
      category: "beach",
      top: false,
      lat: 37.7037,
      lng: 26.6888,
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      summary: "Long south west beach with more space and facilities. Good if you are exploring the Marathokampos side.",
      bestFor: ["Long beach", "Facilities", "South west day", "Swimming"],
      avoidIf: "You only want nearby Karlovasi options.",
      facilities: ["Tavernas", "Beach bars", "Sunbeds in season", "Long beach"],
      kid: 8,
      romance: 7,
      driveFromHotel: "35 to 45 mins",
      pairWith: ["Pythagoras Cave", "Ormos Marathokampou"],
      tags: ["beach", "family", "food nearby", "south west"],
      maps: "https://www.google.com/maps/search/?api=1&query=Votsalakia+Beach+Samos"
    },
    {
      id: "pythagoras-cave",
      name: "Cave of Pythagoras",
      area: "Mount Kerkis",
      category: "experience",
      top: false,
      lat: 37.7182,
      lng: 26.6410,
      image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      summary: "A dramatic mountain side stop with history attached. More adventurous than easy family sightseeing.",
      bestFor: ["Views", "Legend", "Adventure", "Photos"],
      avoidIf: "You want buggy friendly, shade or very simple access.",
      facilities: ["Steps", "Views", "Take water", "Go early"],
      kid: 4,
      romance: 8,
      driveFromHotel: "40 to 50 mins",
      pairWith: ["Votsalakia", "Marathokampos"],
      tags: ["views", "history", "adventure", "mountain"],
      maps: "https://www.google.com/maps/search/?api=1&query=Cave+of+Pythagoras+Samos"
    },
    {
      id: "marathokampos",
      name: "Marathokampos",
      area: "South west",
      category: "village",
      top: false,
      lat: 37.7264,
      lng: 26.6910,
      image: "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=1200&q=80",
      summary: "A useful base for the south west side. Good to combine with beaches, mountain roads and a slower lunch.",
      bestFor: ["South west loop", "Lunch", "Village feel", "Scenery"],
      avoidIf: "You want the easiest postcard harbour experience.",
      facilities: ["Tavernas", "Village", "Mountain roads", "Nearby beaches"],
      kid: 6,
      romance: 7,
      driveFromHotel: "35 to 45 mins",
      pairWith: ["Votsalakia", "Pythagoras Cave"],
      tags: ["village", "food", "south west", "scenic"],
      maps: "https://www.google.com/maps/search/?api=1&query=Marathokampos+Samos"
    },
    {
      id: "pappa-beach",
      name: "Pappa Beach",
      area: "Ireon",
      category: "beach",
      top: false,
      lat: 37.6653,
      lng: 26.8780,
      image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=80",
      summary: "A well liked organised beach near Ireon. Good when you want facilities and a more managed beach day.",
      bestFor: ["Facilities", "Beach bar", "South coast", "Family"],
      avoidIf: "You want wild and empty.",
      facilities: ["Beach bar", "Sunbeds", "Food", "Organised beach"],
      kid: 8,
      romance: 7,
      driveFromHotel: "60 mins",
      pairWith: ["Heraion", "Ireon"],
      tags: ["beach", "family", "food nearby", "organised"],
      maps: "https://www.google.com/maps/search/?api=1&query=Pappa+Beach+Ireon+Samos"
    },
    {
      id: "ireon",
      name: "Ireon",
      area: "South coast",
      category: "village",
      top: false,
      lat: 37.6656,
      lng: 26.8815,
      image: "https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?auto=format&fit=crop&w=1200&q=80",
      summary: "Small seaside village that works well with Heraion and nearby beaches.",
      bestFor: ["Lunch", "Seafront", "Heraion day", "Easy wander"],
      avoidIf: "You are not already on the south coast.",
      facilities: ["Tavernas", "Sea front", "Near Heraion", "Beach nearby"],
      kid: 7,
      romance: 7,
      driveFromHotel: "60 mins",
      pairWith: ["Heraion", "Pappa Beach"],
      tags: ["food", "village", "south", "seafront"],
      maps: "https://www.google.com/maps/search/?api=1&query=Ireon+Samos"
    },
    {
      id: "vathy",
      name: "Vathy and Samos Town",
      area: "East coast",
      category: "town",
      top: false,
      lat: 37.7545,
      lng: 26.9774,
      image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      summary: "The main town area. Useful for a more practical day, museums, shops and wine museum pairing.",
      bestFor: ["Shops", "Museums", "Practical errands", "Wine museum"],
      avoidIf: "You want beach village charm only.",
      facilities: ["Shops", "Cafes", "Museums", "Port"],
      kid: 7,
      romance: 6,
      driveFromHotel: "45 to 55 mins",
      pairWith: ["Samos Wine Museum", "Livadaki Beach"],
      tags: ["town", "practical", "food", "rainy day"],
      maps: "https://www.google.com/maps/search/?api=1&query=Vathy+Samos"
    },
    {
      id: "gagou-beach",
      name: "Gagou Beach",
      area: "Near Vathy",
      category: "beach",
      top: false,
      lat: 37.7620,
      lng: 26.9761,
      image: "https://images.unsplash.com/photo-1520942702018-0862200e6873?auto=format&fit=crop&w=1200&q=80",
      summary: "Small beach close to Samos Town. Handy if you want town plus sea without committing to a remote beach day.",
      bestFor: ["Town plus swim", "Quick stop", "Vathy day", "Low effort"],
      avoidIf: "You are after the prettiest beach on the island.",
      facilities: ["Near town", "Food nearby", "Easy stop", "Small beach"],
      kid: 7,
      romance: 5,
      driveFromHotel: "50 mins",
      pairWith: ["Vathy", "Samos Wine Museum"],
      tags: ["beach", "town", "easy", "food nearby"],
      maps: "https://www.google.com/maps/search/?api=1&query=Gagou+Beach+Samos"
    },
    {
      id: "mykali",
      name: "Mykali Beach",
      area: "South east",
      category: "beach",
      top: false,
      lat: 37.7048,
      lng: 27.0028,
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      summary: "Long beach on the south east side. Useful if Psili Ammos is too busy or you want more space.",
      bestFor: ["Space", "South east day", "Swimming", "Beach facilities"],
      avoidIf: "You want the shortest possible drive from Karlovasi.",
      facilities: ["Long beach", "Some facilities", "Pebbles", "Food nearby"],
      kid: 7,
      romance: 6,
      driveFromHotel: "65 to 75 mins",
      pairWith: ["Psili Ammos", "Pythagoreio"],
      tags: ["beach", "south", "family", "swim"],
      maps: "https://www.google.com/maps/search/?api=1&query=Mykali+Beach+Samos"
    },
    {
      id: "kerveli",
      name: "Kerveli Beach",
      area: "East coast",
      category: "beach",
      top: false,
      lat: 37.7143,
      lng: 27.0366,
      image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
      summary: "Sheltered east coast bay. Good for a quieter scenic swim if you are exploring that side.",
      bestFor: ["Sheltered swim", "Quiet", "East coast", "Scenery"],
      avoidIf: "You do not want a long drive from Karlovasi.",
      facilities: ["Bay", "Tavernas nearby", "Clear water", "Quiet feel"],
      kid: 7,
      romance: 8,
      driveFromHotel: "70 mins",
      pairWith: ["Vathy", "Psili Ammos"],
      tags: ["beach", "quiet", "views", "east"],
      maps: "https://www.google.com/maps/search/?api=1&query=Kerveli+Beach+Samos"
    },
    {
      id: "tsabou",
      name: "Tsabou Beach",
      area: "North coast",
      category: "beach",
      top: false,
      lat: 37.7808,
      lng: 26.8131,
      image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=80",
      summary: "Large pebble beach on the north coast. A good nearby alternative if you are driving between Karlovasi and Kokkari.",
      bestFor: ["Clear water", "North coast", "Space", "Pebble beach"],
      avoidIf: "The wind is hitting the north coast hard.",
      facilities: ["Pebbles", "Food nearby", "Parking", "Water shoes useful"],
      kid: 6,
      romance: 7,
      driveFromHotel: "25 to 30 mins",
      pairWith: ["Agios Konstantinos", "Kokkari"],
      tags: ["beach", "north coast", "swim", "nearish"],
      maps: "https://www.google.com/maps/search/?api=1&query=Tsabou+Beach+Samos"
    },
    {
      id: "agios-konstantinos",
      name: "Agios Konstantinos",
      area: "North coast",
      category: "village",
      top: false,
      lat: 37.7822,
      lng: 26.8194,
      image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
      summary: "Small seafront village that feels less obvious than Kokkari. Good for a relaxed north coast lunch.",
      bestFor: ["Lunch", "Low key", "Sea views", "North coast drive"],
      avoidIf: "You want lots of shops and evening buzz.",
      facilities: ["Tavernas", "Seafront", "Near Tsabou", "Quiet"],
      kid: 7,
      romance: 7,
      driveFromHotel: "25 to 35 mins",
      pairWith: ["Tsabou Beach", "Kokkari"],
      tags: ["food", "village", "seafront", "quiet"],
      maps: "https://www.google.com/maps/search/?api=1&query=Agios+Konstantinos+Samos"
    },
    {
      id: "platanakia-nightingales",
      name: "Nightingale Valley and Platanakia",
      area: "North mountains",
      category: "experience",
      top: false,
      lat: 37.7668,
      lng: 26.8272,
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
      summary: "Green valley area useful for shade, nature and pairing with the mountain villages.",
      bestFor: ["Shade", "Nature", "Village day", "Cooler air"],
      avoidIf: "You want a guaranteed single attraction rather than scenic wandering.",
      facilities: ["Nature", "Shade", "Mountain roads", "Pair with lunch"],
      kid: 7,
      romance: 8,
      driveFromHotel: "30 to 40 mins",
      pairWith: ["Manolates", "Vourliotes"],
      tags: ["nature", "shade", "views", "walk"],
      maps: "https://www.google.com/maps/search/?api=1&query=Nightingale+Valley+Samos"
    },
    {
      id: "archaeological-museum-vathy",
      name: "Archaeological Museum of Samos",
      area: "Vathy",
      category: "history",
      top: false,
      lat: 37.7554,
      lng: 26.9778,
      image: "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=1200&q=80",
      summary: "A useful rainy day or heat escape stop, especially if you want context before or after Heraion.",
      bestFor: ["Rainy day", "Culture", "Heat escape", "History"],
      avoidIf: "Museum patience is low that day.",
      facilities: ["Indoor", "Museum", "Town nearby", "Culture"],
      kid: 5,
      romance: 6,
      driveFromHotel: "50 mins",
      pairWith: ["Vathy", "Samos Wine Museum"],
      tags: ["history", "rainy day", "museum", "vathy"],
      maps: "https://www.google.com/maps/search/?api=1&query=Archaeological+Museum+of+Samos"
    },
    {
      id: "samos-garden-supermarket-karlovasi",
      name: "Local supermarket search",
      area: "Karlovasi",
      category: "practical",
      top: false,
      lat: 37.7927,
      lng: 26.7040,
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
      summary: "One tap search for snacks, water, picnic bits and local bottles near the hotel.",
      bestFor: ["Snacks", "Water", "Balcony drinks", "Picnic supplies"],
      avoidIf: "You are looking for a specific named shop rather than nearby options.",
      facilities: ["Google Maps search", "Practical", "Near hotel", "Supplies"],
      kid: 9,
      romance: 3,
      driveFromHotel: "5 mins",
      pairWith: ["Hotel evening", "Potami Beach"],
      tags: ["practical", "near hotel", "shopping", "supplies"],
      maps: "https://www.google.com/maps/search/?api=1&query=supermarket+near+Erato+by+Samian+Mare+Samos"
    }
  ],
  dayPlans: [
    {
      id: "easy-potami",
      mood: "easy",
      title: "Easy Potami Day",
      subtitle: "Best first full day if you want to keep everything low stress.",
      steps: [
        ["09:30", "Coffee, slow start and beach bag check"],
        ["10:30", "Potami Beach for swimming, stones, paddling and sea air"],
        ["12:30", "Lunch near Potami"],
        ["14:00", "Try the first gentle part of Potami Waterfalls"],
        ["16:00", "Back to hotel for pool, shower and no heroics"]
      ],
      placeIds: ["potami-beach", "potami-waterfalls"]
    },
    {
      id: "postcard-kokkari",
      mood: "romantic",
      title: "Postcard Samos Day",
      subtitle: "Beach, harbour, dinner and the day that feels most like the brochure.",
      steps: [
        ["10:00", "Drive towards Kokkari"],
        ["10:45", "Choose Lemonakia or Tsamadou depending on mood"],
        ["14:00", "Late lunch or early drinks in Kokkari"],
        ["17:30", "Harbour wander and photos"],
        ["19:00", "Dinner by the water if Rocco is still playing ball"]
      ],
      placeIds: ["lemonakia", "tsamadou", "kokkari"]
    },
    {
      id: "rocco-splash",
      mood: "family",
      title: "Rocco Splash Day",
      subtitle: "The child friendly shallow water day, with a longer drive but a big payoff.",
      steps: [
        ["09:00", "Leave before the day gets too hot"],
        ["10:15", "Psili Ammos for sand and shallow water"],
        ["12:30", "Simple lunch nearby"],
        ["14:00", "Optional Mykali or Pythagoreio if everyone is still happy"],
        ["16:00", "Head back before tiredness mutiny"]
      ],
      placeIds: ["psili-ammos-east", "mykali", "pythagoreio"]
    },
    {
      id: "history-harbour",
      mood: "culture",
      title: "Ancient Samos and Harbour Dinner",
      subtitle: "The grown up history day that still ends somewhere pretty.",
      steps: [
        ["09:00", "Heraion before the hottest part of the day"],
        ["11:30", "Pythagoreio harbour for drinks and wandering"],
        ["13:00", "Lunch in Pythagoreio"],
        ["15:00", "Panagia Spiliani or Tunnel of Eupalinos"],
        ["18:00", "Early dinner if the day has gone well"]
      ],
      placeIds: ["heraion", "pythagoreio", "panagia-spiliani", "eupalinos"]
    },
    {
      id: "wine-village",
      mood: "wine",
      title: "Wine and Mountain Villages",
      subtitle: "Best honeymoon feeling without spending the whole day in the car.",
      steps: [
        ["10:00", "Drive into the hills"],
        ["10:45", "Metaxa Liknon if open and booked"],
        ["12:30", "Lunch in Manolates or Vourliotes"],
        ["14:30", "Slow village wander"],
        ["16:00", "Back for an easy evening"]
      ],
      placeIds: ["metaxa-liknon", "manolates", "vourliotes"]
    },
    {
      id: "beer-pythagoreio",
      mood: "beer",
      title: "Local Beer and Pythagoreio",
      subtitle: "A proper local beer tick with harbour time built in.",
      steps: [
        ["10:30", "Head to Pythagoreio"],
        ["11:30", "Short harbour wander"],
        ["12:30", "Lunch and Samos Beer if open"],
        ["14:30", "Optional Panagia Spiliani views"],
        ["16:00", "Buy bottles for a hotel balcony tasting"]
      ],
      placeIds: ["pythagoreio", "samos-beer", "panagia-spiliani"]
    },
    {
      id: "lazy-local",
      mood: "lazy",
      title: "Emergency Lazy Day",
      subtitle: "For the day after a bad night, too much sun or a child based plot twist.",
      steps: [
        ["09:30", "No alarms, no pressure"],
        ["11:00", "Local supermarket snack run"],
        ["12:00", "Pool or short Potami beach visit"],
        ["15:00", "Nap, cartoon, quiet time"],
        ["18:00", "Karlovasi dinner or hotel evening"]
      ],
      placeIds: ["samos-garden-supermarket-karlovasi", "potami-beach", "karlovasi-old-town"]
    }
  ],
  guide: {
    dishes: [
      { greek: "Ρεβιθοκεφτέδες", name: "Revithokeftedes", meaning: "Chickpea fritters", note: "A Samos and Aegean classic. Order these whenever they appear." },
      { greek: "Γεμιστοί κολοκυθοανθοί", name: "Gemisti kolokythoanthoi", meaning: "Stuffed courgette flowers", note: "Delicate, seasonal and very worth trying." },
      { greek: "Μπουρέκια", name: "Bourekia", meaning: "Little pastries, often pumpkin or cheese", note: "Look for these as a local snack or starter." },
      { greek: "Γιουβέτσι", name: "Giouvetsi", meaning: "Slow cooked meat with orzo", note: "Comfort food. Good child friendly option too." },
      { greek: "Χταπόδι", name: "Htapodi", meaning: "Octopus", note: "Usually grilled, in vinegar or cooked with pasta." },
      { greek: "Καλαμάρι", name: "Kalamari", meaning: "Squid", note: "Often fried. Easy seafood gateway." },
      { greek: "Γαρίδες", name: "Garides", meaning: "Prawns", note: "Useful menu word around harbour restaurants." },
      { greek: "Σαρδέλες", name: "Sardeles", meaning: "Sardines", note: "Simple grilled fish option." },
      { greek: "Τυρί", name: "Tyri", meaning: "Cheese", note: "Ask if they have local cheese." },
      { greek: "Μέλι", name: "Meli", meaning: "Honey", note: "Samos honey is worth buying." }
    ],
    wine: [
      { term: "Μοσχάτο Σάμου", say: "Moschato Samou", meaning: "Samos Muscat" },
      { term: "Γλυκό κρασί", say: "Gliko krasi", meaning: "Sweet wine" },
      { term: "Ξηρό", say: "Xiro", meaning: "Dry" },
      { term: "Λευκό", say: "Lefko", meaning: "White" },
      { term: "Κόκκινο", say: "Kokkino", meaning: "Red" },
      { term: "Ροζέ", say: "Roze", meaning: "Rosé" }
    ],
    beer: [
      { term: "Μπύρα", say: "Bira", meaning: "Beer" },
      { term: "Τοπική μπύρα", say: "Topiki bira", meaning: "Local beer" },
      { term: "Βαρελίσια", say: "Varelisia", meaning: "Draught beer" },
      { term: "Μπουκάλι", say: "Boukali", meaning: "Bottle" },
      { term: "Μικρή", say: "Mikri", meaning: "Small" },
      { term: "Μεγάλη", say: "Megali", meaning: "Large" }
    ],
    common: [
      { term: "Κοτόπουλο", say: "Kotopoulo", meaning: "Chicken" },
      { term: "Χοιρινό", say: "Hirino", meaning: "Pork" },
      { term: "Αρνί", say: "Arni", meaning: "Lamb" },
      { term: "Μοσχάρι", say: "Moshari", meaning: "Beef" },
      { term: "Ψάρι", say: "Psari", meaning: "Fish" },
      { term: "Πατάτες", say: "Patates", meaning: "Chips or potatoes" },
      { term: "Σαλάτα", say: "Salata", meaning: "Salad" },
      { term: "Νερό", say: "Nero", meaning: "Water" }
    ]
  },
  phrases: [
    { cat: "Basics", en: "Hello", greek: "Γεια σας", say: "Yassas" },
    { cat: "Basics", en: "Good morning", greek: "Καλημέρα", say: "Kalimera" },
    { cat: "Basics", en: "Good evening", greek: "Καλησπέρα", say: "Kalispera" },
    { cat: "Basics", en: "Thank you", greek: "Ευχαριστώ", say: "Efharisto" },
    { cat: "Basics", en: "Please", greek: "Παρακαλώ", say: "Parakalo" },
    { cat: "Basics", en: "Sorry", greek: "Συγγνώμη", say: "Signomi" },
    { cat: "Restaurant", en: "A table for three please", greek: "Ένα τραπέζι για τρεις παρακαλώ", say: "Ena trapezi gia tris parakalo" },
    { cat: "Restaurant", en: "Can we see the menu please", greek: "Μπορούμε να δούμε το μενού παρακαλώ", say: "Boroume na doume to menu parakalo" },
    { cat: "Restaurant", en: "The bill please", greek: "Τον λογαριασμό παρακαλώ", say: "Ton logariasmo parakalo" },
    { cat: "Restaurant", en: "Do you have a high chair", greek: "Έχετε παιδικό κάθισμα", say: "Ehete pediko kathisma" },
    { cat: "Restaurant", en: "No onions please", greek: "Χωρίς κρεμμύδι παρακαλώ", say: "Horis kremidi parakalo" },
    { cat: "Restaurant", en: "Can we have tap water", greek: "Μπορούμε να έχουμε νερό βρύσης", say: "Boroume na ehume nero vrisis" },
    { cat: "Beer and wine", en: "Do you have local beer", greek: "Έχετε τοπική μπύρα", say: "Ehete topiki bira" },
    { cat: "Beer and wine", en: "A glass of white wine please", greek: "Ένα ποτήρι λευκό κρασί παρακαλώ", say: "Ena potiri lefko krasi parakalo" },
    { cat: "Beer and wine", en: "A bottle of local wine please", greek: "Ένα μπουκάλι τοπικό κρασί παρακαλώ", say: "Ena boukali topiko krasi parakalo" },
    { cat: "Driving", en: "Petrol please", greek: "Βενζίνη παρακαλώ", say: "Venzini parakalo" },
    { cat: "Driving", en: "Diesel please", greek: "Πετρέλαιο παρακαλώ", say: "Petreleo parakalo" },
    { cat: "Driving", en: "Fill it up please", greek: "Γεμίστε το παρακαλώ", say: "Yemiste to parakalo" },
    { cat: "Driving", en: "Where can I park", greek: "Πού μπορώ να παρκάρω", say: "Pou boro na parkaro" },
    { cat: "Shops", en: "How much is this", greek: "Πόσο κάνει αυτό", say: "Poso kani afto" },
    { cat: "Shops", en: "Do you take card", greek: "Δέχεστε κάρτα", say: "Deheste karta" },
    { cat: "Child", en: "Where is the toilet", greek: "Πού είναι η τουαλέτα", say: "Pou ine i toualeta" },
    { cat: "Child", en: "He is nearly four", greek: "Είναι σχεδόν τεσσάρων", say: "Ine shedon tessaron" },
    { cat: "Child", en: "Do you have plain pasta", greek: "Έχετε σκέτα μακαρόνια", say: "Ehete sketa makaronia" },
    { cat: "Pharmacy", en: "I need a pharmacy", greek: "Χρειάζομαι φαρμακείο", say: "Hriazome farmakio" },
    { cat: "Pharmacy", en: "Do you have sunscreen", greek: "Έχετε αντηλιακό", say: "Ehete andiliako" },
    { cat: "Emergency", en: "I need help", greek: "Χρειάζομαι βοήθεια", say: "Hriazome voithia" },
    { cat: "Emergency", en: "Call a doctor please", greek: "Καλέστε γιατρό παρακαλώ", say: "Kaleste giatro parakalo" },
    { cat: "Directions", en: "Where is the beach", greek: "Πού είναι η παραλία", say: "Pou ine i paralia" },
    { cat: "Directions", en: "Is it far", greek: "Είναι μακριά", say: "Ine makria" }
  ]
};
