window.SAMOS_DATA = {
  emergency: [
    { label: "European emergency number", detail: "Call 112 for police, ambulance or fire", phone: "112", maps: "https://www.google.com/maps/search/?api=1&query=emergency+services+near+me" },
    { label: "Ambulance", detail: "Greek ambulance service", phone: "166", maps: "https://www.google.com/maps/search/?api=1&query=hospital+near+me" },
    { label: "Samos General Hospital", detail: "Agios Panteleimon in Samos Town", phone: "+302273083100", maps: "https://www.google.com/maps/search/?api=1&query=Samos+General+Hospital+Agios+Panteleimon" },
    { label: "Karlovasi Health Centre", detail: "Useful from your hotel side of the island", phone: "+302273032222", maps: "https://www.google.com/maps/search/?api=1&query=Health+Center+Karlovasi+Samos" },
    { label: "Nearest pharmacy", detail: "Search nearby pharmacies from wherever you are", phone: "", maps: "https://www.google.com/maps/search/?api=1&query=pharmacy+near+me" },
    { label: "Nearest doctor", detail: "Search nearby doctors or clinics", phone: "", maps: "https://www.google.com/maps/search/?api=1&query=doctor+clinic+near+me" }
  ],
  quickSearches: [
    { label: "Toilets", icon: "🚻", query: "public+toilets+near+me" },
    { label: "Playground", icon: "🛝", query: "playground+near+me" },
    { label: "Supermarket", icon: "🛒", query: "supermarket+near+me" },
    { label: "Petrol", icon: "⛽", query: "petrol+station+near+me" },
    { label: "Ice cream", icon: "🍦", query: "ice+cream+near+me" },
    { label: "ATM", icon: "🏧", query: "ATM+near+me" }
  ],
  places: [
    { id:"potami-waterfalls", name:"Potami Waterfalls", type:"Nature", area:"Karlovasi", top:true, lat:37.792, lng:26.668, image:"https://images.unsplash.com/photo-1542259009477-d625272157b7?auto=format&fit=crop&w=1200&q=75", fallback:"🌿", tags:["family","nature","near hotel","adventure"], bestFor:["Family adventure","Cooler morning","Photos"], short:"Forest walk, river gorge and waterfall swim. Do the easy part with Rocco and only push on if everyone is up for it.", hotel:"10 mins", worth:5, family:4, romance:3, food:3, rocco:true, rainy:false, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Potami+Waterfalls+Samos", pair:["Potami Beach","Karlovasi Old Town"], note:"Take water shoes. Go before lunch. The final bit can be slippery and more adventurous." },
    { id:"potami-beach", name:"Potami Beach", type:"Beach", area:"Karlovasi", top:true, lat:37.798, lng:26.650, image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=75", fallback:"🏖️", tags:["beach","family","near hotel","sunset"], bestFor:["Easy arrival day","Stone throwing","Beach lunch"], short:"Big scenic pebble beach very close to your hotel. Great first day beach and easy to pair with the waterfalls.", hotel:"10 mins", worth:4, family:4, romance:3, food:3, rocco:true, rainy:false, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Potami+Beach+Samos", pair:["Potami Waterfalls","Karlovasi"], note:"Good low effort choice. Pebbles mean beach shoes help." },
    { id:"kokkari", name:"Kokkari", type:"Village", area:"North coast", top:true, lat:37.778, lng:26.892, image:"https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=75", fallback:"🌅", tags:["food","romantic","village","sunset"], bestFor:["Dinner","Harbour wander","Sunset"], short:"The postcard village. Harbour tables, little streets and the place most people want to return to.", hotel:"40 mins", worth:5, family:4, romance:5, food:5, rocco:true, rainy:true, beer:true, wine:true, maps:"https://www.google.com/maps/search/?api=1&query=Kokkari+Samos", pair:["Lemonakia Beach","Tsamadou Beach"], note:"Best as a late afternoon into dinner plan. Great honeymoon evening that can still work with Rocco." },
    { id:"pythagoreio", name:"Pythagoreio", type:"Town", area:"South coast", top:true, lat:37.690, lng:26.943, image:"https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=1200&q=75", fallback:"⚓", tags:["food","history","harbour","beer"], bestFor:["Harbour dinner","Ancient sites","Samos Beer"], short:"Pretty harbour town named after Pythagoras. Pair it with Heraion, Spiliani or Samos Beer.", hotel:"55 mins", worth:5, family:4, romance:5, food:5, rocco:true, rainy:true, beer:true, wine:true, maps:"https://www.google.com/maps/search/?api=1&query=Pythagoreio+Samos", pair:["Samos Beer","Panagia Spiliani","Heraion"], note:"Worth saving for a proper full south coast day." },
    { id:"samos-beer", name:"Samos Beer", type:"Beer", area:"Pythagoreio", top:true, lat:37.690, lng:26.943, image:"https://images.unsplash.com/photo-1532634876-26909d0d4b53?auto=format&fit=crop&w=1200&q=75", fallback:"🍺", tags:["beer","food","rainy","grown up"], bestFor:["Local beer","Early evening","Pythagoreio add on"], short:"The island brewery in Pythagoreio. A very obvious one for you.", hotel:"55 mins", worth:4, family:2, romance:3, food:4, rocco:false, rainy:true, beer:true, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Samos+Beer+Pythagoreio", pair:["Pythagoreio","Panagia Spiliani"], note:"Official brewery tours are advertised in the evening. Check times before driving over." },
    { id:"manolates", name:"Manolates", type:"Village", area:"Mountains", top:true, lat:37.779, lng:26.820, image:"https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=75", fallback:"🏘️", tags:["food","views","romantic","village"], bestFor:["Long lunch","Village wander","Views"], short:"A mountain village made for wandering and lunch. Good when you want a slower, more local day.", hotel:"35 mins", worth:5, family:3, romance:5, food:5, rocco:false, rainy:true, beer:false, wine:true, maps:"https://www.google.com/maps/search/?api=1&query=Manolates+Samos", pair:["Vourliotes","Kokkari"], note:"This is lunch territory. Do not rush it." },
    { id:"vourliotes", name:"Vourliotes", type:"Village", area:"Mountains", top:true, lat:37.771, lng:26.846, image:"https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1200&q=75", fallback:"🍽️", tags:["food","village","quiet","views"], bestFor:["Quiet lunch","Less obvious stop","Local feel"], short:"Quieter village option with a proper slow Greece feel. Good if Manolates feels too busy.", hotel:"40 mins", worth:4, family:3, romance:4, food:4, rocco:false, rainy:true, beer:false, wine:true, maps:"https://www.google.com/maps/search/?api=1&query=Vourliotes+Samos", pair:["Manolates","Kokkari"], note:"Good hidden gem mood. Keep it simple and go for lunch." },
    { id:"livadaki", name:"Livadaki Beach", type:"Beach", area:"North east", top:true, lat:37.792, lng:26.999, image:"https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=75", fallback:"🌊", tags:["beach","family","shallow","pretty"], bestFor:["Shallow water","Family beach day","Photos"], short:"Small, turquoise, shallow and very family friendly when calm. Arrive early if you want the easy version.", hotel:"70 mins", worth:4, family:5, romance:4, food:3, rocco:true, rainy:false, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Livadaki+Beach+Samos", pair:["Samos Town","North east coast"], note:"A drive, but one of the best Rocco friendly beach options." },
    { id:"tsamadou", name:"Tsamadou Beach", type:"Beach", area:"Near Kokkari", top:true, lat:37.795, lng:26.873, image:"https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=75", fallback:"🏝️", tags:["beach","views","romantic","north coast"], bestFor:["Clear water","Beach bars","Scenery"], short:"One of the island beauty spots, with pine slopes and clear water. Better for you two than a pure small child beach.", hotel:"40 mins", worth:5, family:3, romance:5, food:4, rocco:false, rainy:false, beer:true, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Tsamadou+Beach+Samos", pair:["Kokkari","Lemonakia"], note:"Check wind. North coast beaches can be rougher on windy days." },
    { id:"lemonakia", name:"Lemonakia Beach", type:"Beach", area:"Near Kokkari", top:true, lat:37.795, lng:26.883, image:"https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=75", fallback:"🍋", tags:["beach","family","kokkari","swim"], bestFor:["Kokkari add on","Swimming","Easy lunch"], short:"Pretty beach just before Kokkari. A good bridge between proper beach time and a harbour dinner.", hotel:"40 mins", worth:4, family:4, romance:4, food:4, rocco:true, rainy:false, beer:true, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Lemonakia+Beach+Samos", pair:["Kokkari","Tsamadou"], note:"A sensible beach choice when you want Kokkari later." },
    { id:"panagia-spiliani", name:"Panagia Spiliani", type:"View", area:"Pythagoreio", top:true, lat:37.696, lng:26.936, image:"https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?auto=format&fit=crop&w=1200&q=75", fallback:"⛪", tags:["views","history","rainy","romantic"], bestFor:["Views","Cave church","Pythagoreio add on"], short:"Cave monastery above Pythagoreio with a big view payoff. Easy to pair with harbour dinner.", hotel:"55 mins", worth:4, family:3, romance:5, food:2, rocco:false, rainy:true, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Panagia+Spiliani+Samos", pair:["Pythagoreio","Samos Beer"], note:"Good quick stop before dinner in Pythagoreio." },
    { id:"heraion", name:"Heraion of Samos", type:"History", area:"South coast", top:true, lat:37.670, lng:26.884, image:"https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?auto=format&fit=crop&w=1200&q=75", fallback:"🏛️", tags:["history","unesco","culture"], bestFor:["Ancient history","Short cultural stop","South coast day"], short:"Major ancient sanctuary and the key classical site on Samos. More adult interest than Rocco entertainment.", hotel:"60 mins", worth:4, family:2, romance:3, food:1, rocco:false, rainy:false, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Heraion+of+Samos", pair:["Pythagoreio","Psili Ammos"], note:"Go early or late. Not much shade." },
    { id:"eupalinos", name:"Tunnel of Eupalinos", type:"History", area:"Pythagoreio", top:true, lat:37.697, lng:26.933, image:"https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=75", fallback:"🕳️", tags:["history","rainy","engineering"], bestFor:["Ancient engineering","Rainy day","Pythagoreio pairing"], short:"A proper ancient engineering marvel. Fascinating, but not the easiest sell to a small child.", hotel:"55 mins", worth:4, family:2, romance:2, food:1, rocco:false, rainy:true, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Tunnel+of+Eupalinos+Samos", pair:["Pythagoreio","Panagia Spiliani"], note:"Check opening and access options before you go." },
    { id:"wine-museum", name:"Samos Wine Museum", type:"Wine", area:"Samos Town", top:true, lat:37.757, lng:26.976, image:"https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=75", fallback:"🍷", tags:["wine","rainy","grown up","local"], bestFor:["Samos Muscat","Wine geek stop","Rainy day"], short:"Good context for why Samos Muscat matters. Useful for you, probably not a long stop for Rocco.", hotel:"50 mins", worth:4, family:2, romance:4, food:2, rocco:false, rainy:true, beer:false, wine:true, maps:"https://www.google.com/maps/search/?api=1&query=Samos+Wine+Museum", pair:["Samos Town","Livadaki"], note:"Buy Muscat after this, not before. You will understand the styles better." },
    { id:"psili-ammos", name:"Psili Ammos", type:"Beach", area:"South east", top:false, lat:37.704, lng:27.018, image:"https://images.unsplash.com/photo-1520942702018-0862200e6873?auto=format&fit=crop&w=1200&q=75", fallback:"🏖️", tags:["beach","family","sand","shallow"], bestFor:["Small child beach","Sand","Calmer south coast"], short:"Sandy, shallow beach. One of the better options with a nearly four year old.", hotel:"70 mins", worth:4, family:5, romance:3, food:3, rocco:true, rainy:false, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Psili+Ammos+Beach+Samos", pair:["Heraion","Pythagoreio"], note:"Good if the north coast is windy." },
    { id:"karlovasi", name:"Karlovasi Old Town", type:"Town", area:"Karlovasi", top:false, lat:37.790, lng:26.704, image:"https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=75", fallback:"🏘️", tags:["near hotel","food","rainy","easy"], bestFor:["Low effort wander","Coffee","Hotel side evening"], short:"Your local town area. Useful when you want food, supplies or a wander without a big drive.", hotel:"10 mins", worth:3, family:4, romance:2, food:4, rocco:true, rainy:true, beer:true, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Karlovasi+Samos", pair:["Potami Beach","Hotel"], note:"Keep this as your reset option." },
    { id:"metaxa-liknon", name:"Metaxa Liknon", type:"Drink", area:"Vathy", top:false, lat:37.757, lng:26.977, image:"https://images.unsplash.com/photo-1615887023544-3d48d131c80f?auto=format&fit=crop&w=1200&q=75", fallback:"🥃", tags:["drink","rainy","grown up","museum"], bestFor:["Metaxa story","Design led visit","Rainy day"], short:"A grown up drinks and heritage stop around the story of Metaxa and Samos Muscat.", hotel:"50 mins", worth:3, family:1, romance:4, food:2, rocco:false, rainy:true, beer:false, wine:true, maps:"https://www.google.com/maps/search/?api=1&query=Metaxa+Liknon+Samos", pair:["Samos Town","Wine Museum"], note:"More you than Rocco. Pair with a town day." },
    { id:"tsabou", name:"Tsabou Beach", type:"Beach", area:"North coast", top:false, lat:37.793, lng:26.840, image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=75", fallback:"🌊", tags:["beach","north coast","views"], bestFor:["Clear water","Less obvious beach","Scenery"], short:"North coast beach option between Karlovasi and Kokkari. Good if you want a pretty stop without going all the way east.", hotel:"30 mins", worth:4, family:3, romance:4, food:3, rocco:false, rainy:false, beer:false, wine:false, maps:"https://www.google.com/maps/search/?api=1&query=Tsabou+Beach+Samos", pair:["Vourliotes","Kokkari"], note:"Again, check wind before committing to north coast beaches." }
  ],
  eateries: [
    { id:"kokkari-dinner", name:"Kokkari harbour dinner", area:"Kokkari", type:"Dinner", meal:["dinner"], image:"https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=75", short:"Best for a classic Samos evening. Harbour wander, seafood, local wine and people watching.", bestFor:["Sunset dinner","Seafood","Honeymoon"], order:["Grilled octopus","Fresh fish","Samos Muscat"], family:4, romance:5, beer:3, wine:4, maps:"https://www.google.com/maps/search/?api=1&query=restaurants+Kokkari+Samos" },
    { id:"potami-lunch", name:"Potami beach lunch", area:"Potami", type:"Lunch", meal:["lunch"], image:"https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1200&q=75", short:"The easy lunch after beach or waterfalls. Keep expectations simple and enjoy being close to base.", bestFor:["After waterfalls","Low effort","Family"], order:["Greek salad","Souvlaki","Cold beer"], family:5, romance:3, beer:4, wine:2, maps:"https://www.google.com/maps/search/?api=1&query=restaurants+Potami+Beach+Samos" },
    { id:"manolates-lunch", name:"Manolates village lunch", area:"Manolates", type:"Taverna", meal:["lunch"], image:"https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1200&q=75", short:"The kind of long village lunch you hope for in Greece. Slow down and order local.", bestFor:["Village lunch","Local dishes","Views"], order:["Revithokeftedes","Giouvetsi","Local cheese"], family:3, romance:5, beer:3, wine:4, maps:"https://www.google.com/maps/search/?api=1&query=taverna+Manolates+Samos" },
    { id:"karlovasi-breakfast", name:"Karlovasi breakfast and coffee", area:"Karlovasi", type:"Breakfast", meal:["breakfast"], image:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=75", short:"Closest area for coffee, bakery bits, breakfast and supplies. Useful on slower mornings.", bestFor:["Breakfast near hotel","Coffee","Bakery"], order:["Freddo espresso","Spanakopita","Pastry"], family:5, romance:2, beer:1, wine:1, maps:"https://www.google.com/maps/search/?api=1&query=breakfast+coffee+Karlovasi+Samos" },
    { id:"pythagoreio-food", name:"Pythagoreio harbour food", area:"Pythagoreio", type:"Dinner", meal:["lunch","dinner"], image:"https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=75", short:"Loads of options and an easy place to eat after the southern sights. Also your Samos Beer area.", bestFor:["Harbour dinner","Beer","History day"], order:["Seafood","Samos Beer","Local wine"], family:4, romance:4, beer:5, wine:4, maps:"https://www.google.com/maps/search/?api=1&query=restaurants+Pythagoreio+Samos" },
    { id:"beach-bar", name:"North coast beach bar", area:"Tsamadou or Lemonakia", type:"Beach Bar", meal:["lunch","drinks"], image:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=75", short:"For when lunch is basically a lounger, salt, chips and something cold.", bestFor:["Beach lunch","Beer","Low decisions"], order:["Cold beer","Greek salad","Chips for Rocco"], family:4, romance:3, beer:4, wine:2, maps:"https://www.google.com/maps/search/?api=1&query=beach+bar+Tsamadou+Samos" },
    { id:"samos-town-cafe", name:"Samos Town café stop", area:"Vathy", type:"Cafe", meal:["breakfast","lunch"], image:"https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=75", short:"Good for a town wander, coffee and something easy before or after the Wine Museum.", bestFor:["Coffee","Rainy day","Town day"], order:["Freddo cappuccino","Pastry","Ice cream"], family:4, romance:3, beer:1, wine:2, maps:"https://www.google.com/maps/search/?api=1&query=cafe+Vathy+Samos" }
  ],
  dishes: [
    { id:"revithokeftedes", greek:"Ρεβιθοκεφτέδες", name:"Revithokeftedes", image:"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=75", pronounce:"reh vee tho kef TEH des", short:"Chickpea fritters. A classic Samos order when you see it.", look:"Often listed with starters or vegetarian dishes.", worth:5 },
    { id:"giouvetsi", greek:"Γιουβέτσι", name:"Giouvetsi", image:"https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=75", pronounce:"you VET see", short:"Slow cooked meat with orzo pasta. Comfort food territory.", look:"Lamb, beef or goat versions are common.", worth:4 },
    { id:"bourekia", greek:"Μπουρέκια", name:"Bourekia", image:"https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=900&q=75", pronounce:"boo REK ya", short:"Traditional pastry, often with pumpkin or cheese.", look:"Ask if they are homemade.", worth:4 },
    { id:"octopus", greek:"Χταπόδι", name:"Octopus", image:"https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=900&q=75", pronounce:"hta PO thee", short:"Grilled octopus is one of the big Greek island pleasures.", look:"A good sign is octopus hanging outside to dry.", worth:5 },
    { id:"dermatotyri", greek:"Δερματότυρι", name:"Dermatotyri", image:"https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=900&q=75", pronounce:"der ma TO tee ree", short:"Local cheese linked with Samos. Worth trying if it appears.", look:"May appear as local cheese or Samian cheese.", worth:4 },
    { id:"loukoumades", greek:"Λουκουμάδες", name:"Loukoumades", image:"https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=900&q=75", pronounce:"loo koo MA thes", short:"Little fried dough balls with honey. Rocco danger zone.", look:"Dessert menus, cafés and sweet shops.", worth:5 },
    { id:"muscat", greek:"Μοσχάτο Σάμου", name:"Samos Muscat", image:"https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=75", pronounce:"mos HA to SA moo", short:"The island wine. Try sweet Vin Doux and a dry Muscat if you spot one.", look:"Vin Doux, Anthemis, Nectar and dry Muscat.", worth:5 },
    { id:"samos-beer", greek:"Μπύρα Σάμου", name:"Samos Beer", image:"https://images.unsplash.com/photo-1532634876-26909d0d4b53?auto=format&fit=crop&w=900&q=75", pronounce:"BEE ra SA moo", short:"Local island beer. Look for it in Pythagoreio, bars and shops.", look:"Ask: Do you have Samos Beer?", worth:5 }
  ],
  phrases: [
    { cat:"Basics", en:"Hello", el:"Γεια σας", say:"YAH sas" },
    { cat:"Basics", en:"Good morning", el:"Καλημέρα", say:"ka lee MEH ra" },
    { cat:"Basics", en:"Good evening", el:"Καλησπέρα", say:"ka lee SPER a" },
    { cat:"Basics", en:"Thank you", el:"Ευχαριστώ", say:"ef ha ree STO" },
    { cat:"Basics", en:"Please", el:"Παρακαλώ", say:"pa ra ka LO" },
    { cat:"Restaurant", en:"A table for three please", el:"Ένα τραπέζι για τρεις παρακαλώ", say:"EH na tra PE zi ya tris pa ra ka LO" },
    { cat:"Restaurant", en:"The bill please", el:"Τον λογαριασμό παρακαλώ", say:"ton lo gha riaz MO pa ra ka LO" },
    { cat:"Restaurant", en:"Can we have water please?", el:"Μπορούμε να έχουμε νερό παρακαλώ;", say:"bo ROO me na EH khoo me ne RO pa ra ka LO" },
    { cat:"Food", en:"Does this have nuts?", el:"Έχει ξηρούς καρπούς;", say:"EH hee ksee ROOS kar POOS" },
    { cat:"Food", en:"Is this suitable for a child?", el:"Είναι κατάλληλο για παιδί;", say:"EE ne ka TA lee lo ya pe THEE" },
    { cat:"Bar", en:"One beer please", el:"Μία μπύρα παρακαλώ", say:"MEE a BEE ra pa ra ka LO" },
    { cat:"Wine", en:"A glass of local white wine please", el:"Ένα ποτήρι τοπικό λευκό κρασί παρακαλώ", say:"EH na po TEE ri to pee KO lef KO kra SEE pa ra ka LO" },
    { cat:"Driving", en:"Fill it up please", el:"Γεμίστε το παρακαλώ", say:"ye MEE ste to pa ra ka LO" },
    { cat:"Driving", en:"Petrol", el:"Βενζίνη", say:"ven ZEE nee" },
    { cat:"Driving", en:"Diesel", el:"Πετρέλαιο", say:"pe TREL eh o" },
    { cat:"Child", en:"Where is the toilet?", el:"Πού είναι η τουαλέτα;", say:"poo EE ne ee too a LE ta" },
    { cat:"Child", en:"Do you have a high chair?", el:"Έχετε παιδικό καρεκλάκι;", say:"EH heh te pe thee KO ka re KLA kee" },
    { cat:"Emergency", en:"My child is unwell", el:"Το παιδί μου δεν είναι καλά", say:"to pe THEE moo then EE ne ka LA" },
    { cat:"Emergency", en:"We need a doctor", el:"Χρειαζόμαστε γιατρό", say:"hree a ZO mas te ya TRO" },
    { cat:"Emergency", en:"Where is the nearest pharmacy?", el:"Πού είναι το κοντινότερο φαρμακείο;", say:"poo EE ne to kon dee NO te ro far ma KEE o" }
  ],
  tryList: [
    { id:"try-revithokeftedes", type:"Food", label:"Revithokeftedes" },
    { id:"try-octopus", type:"Food", label:"Grilled octopus" },
    { id:"try-giouvetsi", type:"Food", label:"Giouvetsi" },
    { id:"try-bourekia", type:"Food", label:"Bourekia" },
    { id:"try-loukoumades", type:"Sweet", label:"Loukoumades" },
    { id:"try-vindoux", type:"Wine", label:"Samos Vin Doux" },
    { id:"try-drymuscat", type:"Wine", label:"Dry Muscat" },
    { id:"try-samosbeer", type:"Beer", label:"Samos Beer" }
  ]
};
