window.SAMOS_DATA = {
  base: {
    hotel: "Erato by Samian Mare",
    dates: "20 to 27 September",
    maps: "https://www.google.com/maps/search/?api=1&query=Erato+by+Samian+Mare+Samos"
  },
  places: [
    {id:"potami-beach", name:"Potami Beach", type:"Beach", area:"Karlovasi", drive:"10 mins", kid:8, romance:8, tags:["nearby","sunset","swim","pebbles"], blurb:"Your easy first beach from Karlovasi. Pebbly, scenic, relaxed and useful for a low effort arrival day.", tip:"Bring water shoes if you have them. Pair with the waterfalls or a sunset drink.", maps:"https://www.google.com/maps/search/?api=1&query=Potami+Beach+Samos"},
    {id:"potami-waterfalls", name:"Potami Waterfalls", type:"Nature", area:"Karlovasi", drive:"10 mins", kid:7, romance:8, tags:["nearby","adventure","shade","water"], blurb:"Forest walk, wooden bridges, river gorge and cool water. The first section is family friendly, the final watery bit is more adventurous.", tip:"For a nearly four year old, enjoy the shaded walk and judge the water section when you arrive.", maps:"https://www.google.com/maps/search/?api=1&query=Potami+Waterfalls+Samos"},
    {id:"agios-nikolaos-potami", name:"Agios Nikolaos Church Potami", type:"Viewpoint", area:"Karlovasi", drive:"10 mins", kid:6, romance:9, tags:["nearby","views","sunset"], blurb:"Small hilltop church above Potami with one of the easiest big view payoffs near your base.", tip:"Good for photos before or after Potami Beach.", maps:"https://www.google.com/maps/search/?api=1&query=Agios+Nikolaos+Potami+Samos"},
    {id:"karlovasi-old-town", name:"Karlovasi Old Town", type:"Town", area:"Karlovasi", drive:"5 mins", kid:7, romance:7, tags:["nearby","evening","local"], blurb:"Often skipped by visitors racing across the island, but worth a wander for old mansions, squares and a more local feel.", tip:"Use it for easy dinners and supermarket runs rather than treating every evening as a big drive.", maps:"https://www.google.com/maps/search/?api=1&query=Karlovasi+Old+Town+Samos"},
    {id:"kokkari", name:"Kokkari", type:"Village", area:"North coast", drive:"40 mins", kid:8, romance:10, tags:["harbour","dinner","views","romantic"], blurb:"The postcard village. Harbour, tavernas, blue shutters, fishing boats and very easy evening wandering.", tip:"Excellent for a honeymoon evening that still works with a child in tow.", maps:"https://www.google.com/maps/search/?api=1&query=Kokkari+Samos"},
    {id:"lemonakia", name:"Lemonakia Beach", type:"Beach", area:"Near Kokkari", drive:"40 mins", kid:8, romance:8, tags:["swim","organised","clear-water"], blurb:"Pretty, organised beach near Kokkari with clear water and a convenient north coast location.", tip:"Combine with Kokkari for lunch or dinner.", maps:"https://www.google.com/maps/search/?api=1&query=Lemonakia+Beach+Samos"},
    {id:"tsamadou", name:"Tsamadou Beach", type:"Beach", area:"Near Kokkari", drive:"42 mins", kid:6, romance:9, tags:["views","swim","pebbles"], blurb:"One of Samos' most striking beaches, with turquoise water and pine covered slopes above the bay.", tip:"The eastern end has historically been naturist, so choose your spot accordingly with Rocco.", maps:"https://www.google.com/maps/search/?api=1&query=Tsamadou+Beach+Samos"},
    {id:"tsabou", name:"Tsabou Beach", type:"Beach", area:"North coast", drive:"30 mins", kid:6, romance:7, tags:["pebbles","spacious","swim"], blurb:"A broader north coast beach option, useful when you want space and dramatic water rather than sandcastles.", tip:"Can be wavier in north winds.", maps:"https://www.google.com/maps/search/?api=1&query=Tsabou+Beach+Samos"},
    {id:"agios-konstantinos", name:"Agios Konstantinos", type:"Village", area:"North coast", drive:"28 mins", kid:7, romance:7, tags:["local","seafront","lunch"], blurb:"Low key seafront village that feels less staged than the obvious resort stops.", tip:"Good lunch stop between Karlovasi and Kokkari.", maps:"https://www.google.com/maps/search/?api=1&query=Agios+Konstantinos+Samos"},
    {id:"manolates", name:"Manolates", type:"Village", area:"Mountains", drive:"40 mins", kid:6, romance:9, tags:["mountain","lunch","views","slow"], blurb:"Beautiful mountain village with lanes, cats, workshops and tavernas. Feels like a holiday within the holiday.", tip:"Do not rush this one. Go for lunch, wander, then leave happy.", maps:"https://www.google.com/maps/search/?api=1&query=Manolates+Samos"},
    {id:"vourliotes", name:"Vourliotes", type:"Village", area:"Mountains", drive:"45 mins", kid:6, romance:9, tags:["mountain","quiet","wine"], blurb:"Quiet mountain village above the north coast and close to some of the island's wine story.", tip:"Pair with Metaxa Liknon if you book ahead.", maps:"https://www.google.com/maps/search/?api=1&query=Vourliotes+Samos"},
    {id:"metaxa-liknon", name:"Metaxa Liknon", type:"Wine", area:"Vourliotes", drive:"45 mins", kid:3, romance:10, tags:["book-ahead","wine","grown-up","views"], blurb:"A polished Samos Muscat and Metaxa experience in a vineyard landscape near Vourliotes.", tip:"Book ahead. Best used as your grown up honeymoon wine moment if childcare and timings work.", maps:"https://www.google.com/maps/search/?api=1&query=Metaxa+Liknon+Samos"},
    {id:"pythagoreio", name:"Pythagoreio", type:"Town", area:"South coast", drive:"60 mins", kid:8, romance:9, tags:["harbour","history","dinner","wander"], blurb:"Pretty harbour town named after Pythagoras. A strong full day anchor with history, food and evening atmosphere.", tip:"Do Heraion or the tunnel first, then finish here for dinner.", maps:"https://www.google.com/maps/search/?api=1&query=Pythagoreio+Samos"},
    {id:"heraion", name:"Heraion of Samos", type:"History", area:"South coast", drive:"65 mins", kid:5, romance:7, tags:["ancient","unesco","culture"], blurb:"Major ancient sanctuary of Hera and one of the island's key archaeological sites.", tip:"Go earlier in the day and keep the visit short with Rocco.", maps:"https://www.google.com/maps/search/?api=1&query=Heraion+of+Samos"},
    {id:"eupalinos", name:"Tunnel of Eupalinos", type:"History", area:"Pythagoreio", drive:"60 mins", kid:4, romance:6, tags:["ancient","rainy","engineering"], blurb:"Ancient engineering marvel near Pythagoreio. Memorable, but more adult interesting than toddler magical.", tip:"Check opening and access before driving over.", maps:"https://www.google.com/maps/search/?api=1&query=Tunnel+of+Eupalinos+Samos"},
    {id:"panagia-spiliani", name:"Panagia Spiliani Monastery", type:"Viewpoint", area:"Pythagoreio", drive:"60 mins", kid:6, romance:9, tags:["views","cave","culture"], blurb:"Cave monastery above Pythagoreio with big views across the south coast.", tip:"An excellent add on to a Pythagoreio day.", maps:"https://www.google.com/maps/search/?api=1&query=Panagia+Spiliani+Samos"},
    {id:"samos-beer", name:"Samos Beer", type:"Beer", area:"Pythagoreio", drive:"60 mins", kid:3, romance:7, tags:["beer","local","grown-up"], blurb:"The island brewery in Pythagoreio. Look for local pours rather than defaulting to Mythos everywhere.", tip:"Their own site lists free guided tours from 18:00 to 20:00, but check current hours before going.", maps:"https://www.google.com/maps/search/?api=1&query=Samos+Beer+Pythagoreio"},
    {id:"samos-wine-museum", name:"Samos Wine Museum", type:"Wine", area:"Samos Town", drive:"55 mins", kid:4, romance:8, tags:["wine","rainy","museum"], blurb:"Useful stop for understanding Samos Muscat and the cooperative wine history of the island.", tip:"Good rainy day or wine nerd stop. Pair with Samos Town.", maps:"https://www.google.com/maps/search/?api=1&query=Samos+Wine+Museum"},
    {id:"samos-town", name:"Samos Town Vathy", type:"Town", area:"East", drive:"55 mins", kid:7, romance:7, tags:["shops","museum","harbour"], blurb:"The island capital, with harbour, shops and museums. More practical than postcard pretty, but useful.", tip:"Pair with the Wine Museum or Archaeological Museum.", maps:"https://www.google.com/maps/search/?api=1&query=Samos+Town+Vathy"},
    {id:"livadaki", name:"Livadaki Beach", type:"Beach", area:"North east", drive:"75 mins", kid:9, romance:8, tags:["shallow","turquoise","family"], blurb:"Small, shallow, turquoise bay. A favourite for families when the road and conditions are kind.", tip:"The access road can be rough. Check car hire rules about unpaved roads.", maps:"https://www.google.com/maps/search/?api=1&query=Livadaki+Beach+Samos"},
    {id:"psili-ammos-east", name:"Psili Ammos Beach", type:"Beach", area:"South east", drive:"75 mins", kid:10, romance:7, tags:["sand","shallow","family"], blurb:"One of the best family beach options thanks to sand and very shallow water.", tip:"There are multiple Psili Ammos beaches. This app means the south east one near Mykali.", maps:"https://www.google.com/maps/search/?api=1&query=Psili+Ammos+Beach+Mykali+Samos"},
    {id:"mykali", name:"Mykali Beach", type:"Beach", area:"South east", drive:"70 mins", kid:7, romance:6, tags:["long","organised","swim"], blurb:"Long beach with organised sections and bright water, useful if Psili Ammos feels too busy.", tip:"Good for a south east beach day.", maps:"https://www.google.com/maps/search/?api=1&query=Mykali+Beach+Samos"},
    {id:"pappa-beach", name:"Pappa Beach", type:"Beach", area:"Ireon", drive:"70 mins", kid:8, romance:8, tags:["organised","family","food"], blurb:"Well liked organised beach near Ireon, often praised for its setting and hospitality.", tip:"Could work nicely with Heraion and Ireon.", maps:"https://www.google.com/maps/search/?api=1&query=Pappa+Beach+Ireon+Samos"},
    {id:"ireon", name:"Ireon", type:"Village", area:"South coast", drive:"68 mins", kid:7, romance:7, tags:["seafront","dinner","history"], blurb:"Small south coast village near Heraion with tavernas and a slower seafront feel.", tip:"Easy food stop after Heraion.", maps:"https://www.google.com/maps/search/?api=1&query=Ireon+Samos"},
    {id:"kaladakia", name:"Kaladakia Beach", type:"Beach", area:"South west", drive:"45 mins", kid:6, romance:8, tags:["cave","swim","adventure"], blurb:"South west beach known for clear water and a small cave swim when conditions suit.", tip:"Better with confident swimmers and calm water.", maps:"https://www.google.com/maps/search/?api=1&query=Kaladakia+Beach+Samos"},
    {id:"balos", name:"Balos Beach", type:"Beach", area:"South west", drive:"50 mins", kid:7, romance:8, tags:["quiet","swim","lunch"], blurb:"Relaxed south west beach option for a slower day away from the famous north coast beaches.", tip:"Useful when north winds make the north coast rougher.", maps:"https://www.google.com/maps/search/?api=1&query=Balos+Beach+Samos"},
    {id:"votsalakia", name:"Votsalakia Kampos", type:"Beach", area:"Marathokampos", drive:"45 mins", kid:8, romance:7, tags:["family","long","west"], blurb:"Long beach and resort strip under Mount Kerkis. Practical for a west side family beach day.", tip:"Good when you want facilities without crossing the whole island.", maps:"https://www.google.com/maps/search/?api=1&query=Votsalakia+Samos"},
    {id:"mikro-seitani", name:"Mikro Seitani", type:"Beach", area:"North west", drive:"Drive plus hike", kid:3, romance:9, tags:["wild","hike","views"], blurb:"Wild beach reached by walking. Beautiful, but not a casual toddler beach day.", tip:"Maybe one for a future trip unless everyone is feeling adventurous.", maps:"https://www.google.com/maps/search/?api=1&query=Mikro+Seitani+Samos"},
    {id:"megalo-seitani", name:"Megalo Seitani", type:"Beach", area:"North west", drive:"Drive plus longer hike", kid:2, romance:10, tags:["wild","hike","remote"], blurb:"Remote, dramatic beach and protected natural area. Gorgeous, but a proper expedition.", tip:"Only attempt if you plan it properly and the family is up for a hike.", maps:"https://www.google.com/maps/search/?api=1&query=Megalo+Seitani+Samos"},
    {id:"vakakis", name:"Vakakis Domaine", type:"Wine", area:"Karlovasi", drive:"15 mins", kid:3, romance:9, tags:["wine","nearby","book-ahead"], blurb:"Small quality focused winery founded in 2011, with interest in local and Aegean varieties.", tip:"Because it is near Karlovasi, this is the easiest proper wine stop from your hotel if you can arrange a visit.", maps:"https://www.google.com/maps/search/?api=1&query=Vakakis+Domaine+Samos"},
    {id:"orizontas", name:"Orizontas Samos", type:"Restaurant", area:"Platanos", drive:"35 mins", kid:6, romance:10, tags:["views","dinner","sunset"], blurb:"Mountain village dining with big views. Often appears in wine and food day recommendations.", tip:"Book ahead if you want a proper sunset meal.", maps:"https://www.google.com/maps/search/?api=1&query=Orizontas+Samos+Platanos"},
    {id:"platanos", name:"Platanos", type:"Village", area:"Mountains", drive:"35 mins", kid:6, romance:8, tags:["mountain","views","food"], blurb:"Mountain village that can work as a gentler alternative to crossing the island for atmosphere.", tip:"Pair with Orizontas or a west side drive.", maps:"https://www.google.com/maps/search/?api=1&query=Platanos+Samos"},
    {id:"archaeological-museum", name:"Archaeological Museum of Samos", type:"History", area:"Samos Town", drive:"55 mins", kid:5, romance:6, tags:["museum","rainy","culture"], blurb:"Useful cultural stop in Samos Town, especially if you want an indoor option.", tip:"Good backup if weather turns or beach energy dips.", maps:"https://www.google.com/maps/search/?api=1&query=Archaeological+Museum+of+Samos"}
  ],
  days: [
    {id:"arrival-soft", title:"Soft landing near Karlovasi", mood:"Easy, close and low risk", bestFor:"Arrival or tired day", stops:["potami-beach","potami-waterfalls","agios-nikolaos-potami","karlovasi-old-town"], plan:["Slow breakfast and no big drive","Potami Beach for an easy swim","Lunch near Potami or Karlovasi","Short shaded walk at Potami Waterfalls if Rocco has energy","Sunset at Agios Nikolaos or an easy Karlovasi dinner"]},
    {id:"postcard-north", title:"Postcard north coast", mood:"Pretty villages and blue water", bestFor:"Classic Samos day", stops:["agios-konstantinos","lemonakia","tsamadou","kokkari"], plan:["Drive the north coast after breakfast","Coffee or short stop in Agios Konstantinos","Swim at Lemonakia or Tsamadou","Late lunch or early dinner in Kokkari","Harbour wander and photos before heading back"]},
    {id:"ancient-south", title:"Ancient Samos and harbour dinner", mood:"History with a reward at the end", bestFor:"One big full day", stops:["heraion","ireon","panagia-spiliani","pythagoreio"], plan:["Start early and visit Heraion before the heat","Lunch in Ireon or Pythagoreio","Visit Panagia Spiliani for the cave and views","Wander Pythagoreio harbour","Dinner by the water"]},
    {id:"mountain-lunch", title:"Mountain village lunch", mood:"Slow, scenic and very Greek", bestFor:"Cooler day or lazy exploring", stops:["manolates","vourliotes","metaxa-liknon","kokkari"], plan:["Drive into the hills late morning","Wander Manolates","Long lunch in a mountain taverna","Optional Vourliotes or Metaxa Liknon if booked","Finish with a short Kokkari stop if everyone is still happy"]},
    {id:"wine-nerd", title:"Samos wine day", mood:"Muscat, views and grown up treats", bestFor:"Honeymoon wine moment", stops:["vakakis","samos-wine-museum","metaxa-liknon","orizontas"], plan:["Arrange Vakakis or Metaxa Liknon ahead if possible","Use Samos Wine Museum for context","Look out for dry Muscat as well as sweet wines","Buy one bottle for a balcony tasting","Finish with a view led dinner if timings work"]},
    {id:"family-sand", title:"Family beach day", mood:"Sand, shallow water and minimal stress", bestFor:"Rocco centric day", stops:["psili-ammos-east","mykali","pappa-beach","ireon"], plan:["Leave earlier because it is a longer drive","Make Psili Ammos the main event","Keep Mykali or Pappa Beach as backup","Simple lunch near the beach","Avoid adding too much history unless everyone is in the mood"]},
    {id:"west-coast", title:"West and south west explorer", mood:"Closer beaches and mountain views", bestFor:"Lower drive day from Karlovasi", stops:["votsalakia","kaladakia","balos","platanos"], plan:["Head towards Marathokampos","Choose Votsalakia for facilities or Kaladakia for adventure","Late lunch near the coast","Drive back via Platanos if you want views","Easy hotel evening"]}
  ],
  food: [
    {greek:"Ρεβιθοκεφτέδες", latin:"Revithokeftedes", meaning:"Chickpea fritters", note:"A classic Aegean dish and a must order if you see it."},
    {greek:"Σαμιώτικο Γιουβέτσι", latin:"Samiotiko giouvetsi", meaning:"Samian meat and orzo bake", note:"Usually lamb or beef with orzo in tomato sauce."},
    {greek:"Χταπόδι", latin:"Htapodi", meaning:"Octopus", note:"Often grilled. If you see it drying outside, that is usually a good sign."},
    {greek:"Καλαμάρι", latin:"Kalamari", meaning:"Squid", note:"Grilled or fried. Easy holiday ordering."},
    {greek:"Γαρίδες", latin:"Garides", meaning:"Prawns", note:"Good with local white wine or dry Muscat."},
    {greek:"Κολοκυθοκεφτέδες", latin:"Kolokithokeftedes", meaning:"Courgette fritters", note:"A very safe table order for adults and children."},
    {greek:"Ντολμαδάκια", latin:"Dolmadakia", meaning:"Stuffed vine leaves", note:"Good cold starter with lemon and olive oil."},
    {greek:"Μπουρέκια", latin:"Bourekia", meaning:"Traditional pastries", note:"Look for cheese or pumpkin versions."},
    {greek:"Ντόπιο τυρί", latin:"Dopio tyri", meaning:"Local cheese", note:"Ask for local cheese rather than generic feta every time."},
    {greek:"Μέλι", latin:"Meli", meaning:"Honey", note:"Samos honey is worth buying for home."},
    {greek:"Μοσχάτο Σάμου", latin:"Moschato Samou", meaning:"Samos Muscat", note:"The island signature wine, from fresh dry examples to famous sweet styles."}
  ],
  drinks: [
    {name:"Samos Beer", type:"Beer", lookFor:"Valsamo Ale and whatever is fresh on tap", note:"Island brewed beer from Pythagoreio. A better order than default lager when available."},
    {name:"Mythos", type:"Beer", lookFor:"Common Greek lager", note:"Everywhere, reliable, not the local discovery."},
    {name:"Fix", type:"Beer", lookFor:"Common Greek lager", note:"Good fridge beer, but not a Samos specific one."},
    {name:"Alpha", type:"Beer", lookFor:"Common Greek lager", note:"Likely to appear in beach bars and tavernas."},
    {name:"Samos Vin Doux", type:"Wine", lookFor:"Sweet Muscat", note:"Classic dessert style. Try with honey, pastries or blue cheese if available."},
    {name:"Samos Anthemis", type:"Wine", lookFor:"Aged sweet Muscat", note:"Richer, deeper, more marmalade and dried fruit territory."},
    {name:"Dry Muscat", type:"Wine", lookFor:"Ξηρό Μοσχάτο", note:"Potentially the most interesting holiday discovery if you usually avoid sweet wine."},
    {name:"Vakakis wines", type:"Wine", lookFor:"Small production bottles", note:"A good name to look for near Karlovasi and in better restaurants."},
    {name:"Metaxa", type:"Spirit", lookFor:"Metaxa cocktails or tastings", note:"Not wine, but closely tied to Samos Muscat through LIKNON."}
  ],
  phrases: [
    {en:"Hello", greek:"Γεια σας", say:"YAH sas"},
    {en:"Good morning", greek:"Καλημέρα", say:"ka lee MEH ra"},
    {en:"Good evening", greek:"Καλησπέρα", say:"ka lee SPEH ra"},
    {en:"Thank you", greek:"Ευχαριστώ", say:"ef ha ree STO"},
    {en:"Please", greek:"Παρακαλώ", say:"pa ra ka LO"},
    {en:"Yes", greek:"Ναι", say:"neh"},
    {en:"No", greek:"Όχι", say:"OH hee"},
    {en:"Sorry", greek:"Συγγνώμη", say:"see GHNO mee"},
    {en:"Do you speak English?", greek:"Μιλάτε αγγλικά;", say:"mee LAH teh ang lee KAH"},
    {en:"A table for three please", greek:"Ένα τραπέζι για τρεις παρακαλώ", say:"EH na tra PEH zee ya trees pa ra ka LO"},
    {en:"The bill please", greek:"Τον λογαριασμό παρακαλώ", say:"ton lo ga ria ZMO pa ra ka LO"},
    {en:"Water please", greek:"Νερό παρακαλώ", say:"neh RO pa ra ka LO"},
    {en:"One beer please", greek:"Μία μπύρα παρακαλώ", say:"MEE a BEE ra pa ra ka LO"},
    {en:"One glass of white wine please", greek:"Ένα ποτήρι λευκό κρασί παρακαλώ", say:"EH na po TEE ree lef KO kra SEE pa ra ka LO"},
    {en:"Where is the toilet?", greek:"Πού είναι η τουαλέτα;", say:"poo EE neh ee too a LEH ta"},
    {en:"Do you have a high chair?", greek:"Έχετε παιδικό κάθισμα;", say:"EH heh teh peh thee KO KA thee sma"},
    {en:"Petrol", greek:"Βενζίνη", say:"ven ZEE nee"},
    {en:"Diesel", greek:"Πετρέλαιο", say:"peh TREH leh oh"},
    {en:"Fill it up please", greek:"Γεμίστε το παρακαλώ", say:"yeh MEE steh to pa ra ka LO"},
    {en:"Can I pay by card?", greek:"Μπορώ να πληρώσω με κάρτα;", say:"bo RO na plee RO so meh KAR ta"}
  ],
  practical: [
    {title:"Nearest pharmacy", maps:"https://www.google.com/maps/search/?api=1&query=pharmacy+near+Erato+by+Samian+Mare+Samos", note:"Use this instead of saving one specific pharmacy in case opening hours change."},
    {title:"Nearest petrol station", maps:"https://www.google.com/maps/search/?api=1&query=petrol+station+near+Erato+by+Samian+Mare+Samos", note:"Useful before longer east or south coast days."},
    {title:"Nearest supermarket", maps:"https://www.google.com/maps/search/?api=1&query=supermarket+near+Erato+by+Samian+Mare+Samos", note:"For water, snacks, fruit, nappies or picnic bits."},
    {title:"Nearest ATM", maps:"https://www.google.com/maps/search/?api=1&query=ATM+near+Erato+by+Samian+Mare+Samos", note:"Still useful for smaller tavernas and beach spots."},
    {title:"Hospital or medical help", maps:"https://www.google.com/maps/search/?api=1&query=hospital+Samos", note:"Saved as a quick search rather than a promise about emergency routing."}
  ],
  tips: [
    "September is a strong month for Samos: warm sea, lower crowds and harvest season energy.",
    "With a nearly four year old, plan one main thing per day, then keep everything else optional.",
    "North coast beaches can be rougher with north winds. South coast beaches are useful backups.",
    "Water shoes are handy because many of the best beaches are pebbly.",
    "Book grown up experiences like Metaxa Liknon or winery visits ahead rather than trying to wing it.",
    "Use Google Maps buttons in the app for navigation, but check live opening hours before setting off."
  ]
};
